// Code generated by gamedata/gen. DO NOT EDIT.

package v1

import (
	"github.com/kweezl/spacecraft-corporation/internal/gamedata/schema"
)

var SpaceObjects = map[schema.GDID]schema.SpaceObject{"Empty": schema.SpaceObject{ID: "Empty", Owner: "", Building: ""}, "Station_Cairn": schema.SpaceObject{ID: "Station_Cairn", Owner: "TheCo", Building: "SpaceStation3"}, "Station_Horizon": schema.SpaceObject{ID: "Station_Horizon", Owner: "TheCo", Building: "SpaceStation5"}, "Station_Justice": schema.SpaceObject{ID: "Station_Justice", Owner: "TheCo", Building: "SpaceStation4"}, "Station_Start": schema.SpaceObject{ID: "Station_Start", Owner: "TheCo", Building: "SpaceStation1"}, "Station_Terminus": schema.SpaceObject{ID: "Station_Terminus", Owner: "TheCo", Building: "SpaceStation2"}, "Station_Threshold": schema.SpaceObject{ID: "Station_Threshold", Owner: "TheCo", Building: "SpaceStation0"}, "Test_Pirates": schema.SpaceObject{ID: "Test_Pirates", Owner: "SpacePirates", Building: "RegionPiratesSpawn"}}
