// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// IsApproved provides a mock function with given fields: ctx, serverID
func (_m *MockRepository) IsApproved(ctx context.Context, serverID string) (bool, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for IsApproved")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsApproved'
type MockRepository_IsApproved_Call struct {
	*mock.Call
}

// IsApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockRepository_Expecter) IsApproved(ctx interface{}, serverID interface{}) *MockRepository_IsApproved_Call {
	return &MockRepository_IsApproved_Call{Call: _e.mock.On("IsApproved", ctx, serverID)}
}

func (_c *MockRepository_IsApproved_Call) Run(run func(ctx context.Context, serverID string)) *MockRepository_IsApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IsApproved_Call) Return(_a0 bool, _a1 error) *MockRepository_IsApproved_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsApproved_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_IsApproved_Call {
	_c.Call.Return(run)
	return _c
}

// LogEvent provides a mock function with given fields: ctx, serverID, eventType
func (_m *MockRepository) LogEvent(ctx context.Context, serverID string, eventType string) error {
	ret := _m.Called(ctx, serverID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for LogEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serverID, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_LogEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogEvent'
type MockRepository_LogEvent_Call struct {
	*mock.Call
}

// LogEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - eventType string
func (_e *MockRepository_Expecter) LogEvent(ctx interface{}, serverID interface{}, eventType interface{}) *MockRepository_LogEvent_Call {
	return &MockRepository_LogEvent_Call{Call: _e.mock.On("LogEvent", ctx, serverID, eventType)}
}

func (_c *MockRepository_LogEvent_Call) Run(run func(ctx context.Context, serverID string, eventType string)) *MockRepository_LogEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_LogEvent_Call) Return(_a0 error) *MockRepository_LogEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_LogEvent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_LogEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, serverID, name, inList
func (_m *MockRepository) Upsert(ctx context.Context, serverID string, name string, inList bool) (bool, error) {
	ret := _m.Called(ctx, serverID, name, inList)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (bool, error)); ok {
		return rf(ctx, serverID, name, inList)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) bool); ok {
		r0 = rf(ctx, serverID, name, inList)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, serverID, name, inList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - name string
//   - inList bool
func (_e *MockRepository_Expecter) Upsert(ctx interface{}, serverID interface{}, name interface{}, inList interface{}) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, serverID, name, inList)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, serverID string, name string, inList bool)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(isNew bool, err error) *MockRepository_Upsert_Call {
	_c.Call.Return(isNew, err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(context.Context, string, string, bool) (bool, error)) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
