version: "2"
run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kweezl/spacecraft-corporation)