with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/kweezl/spacecraft-corporation/internal/features/ping:
    interfaces:
      Repository:
