// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	bases "github.com/kweezl/spacecraft-corporation/internal/features/bases"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddExtractor provides a mock function with given fields: ctx, o, baseID, resourceName, limit
func (_m *MockRepository) AddExtractor(ctx context.Context, o bases.Ownership, baseID uuid.UUID, resourceName string, limit int) error {
	ret := _m.Called(ctx, o, baseID, resourceName, limit)

	if len(ret) == 0 {
		panic("no return value specified for AddExtractor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID, string, int) error); ok {
		r0 = rf(ctx, o, baseID, resourceName, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddExtractor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExtractor'
type MockRepository_AddExtractor_Call struct {
	*mock.Call
}

// AddExtractor is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - baseID uuid.UUID
//   - resourceName string
//   - limit int
func (_e *MockRepository_Expecter) AddExtractor(ctx interface{}, o interface{}, baseID interface{}, resourceName interface{}, limit interface{}) *MockRepository_AddExtractor_Call {
	return &MockRepository_AddExtractor_Call{Call: _e.mock.On("AddExtractor", ctx, o, baseID, resourceName, limit)}
}

func (_c *MockRepository_AddExtractor_Call) Run(run func(ctx context.Context, o bases.Ownership, baseID uuid.UUID, resourceName string, limit int)) *MockRepository_AddExtractor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_AddExtractor_Call) Return(_a0 error) *MockRepository_AddExtractor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddExtractor_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID, string, int) error) *MockRepository_AddExtractor_Call {
	_c.Call.Return(run)
	return _c
}

// AddProduction provides a mock function with given fields: ctx, o, baseID, itemName, limit
func (_m *MockRepository) AddProduction(ctx context.Context, o bases.Ownership, baseID uuid.UUID, itemName string, limit int) error {
	ret := _m.Called(ctx, o, baseID, itemName, limit)

	if len(ret) == 0 {
		panic("no return value specified for AddProduction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID, string, int) error); ok {
		r0 = rf(ctx, o, baseID, itemName, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddProduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduction'
type MockRepository_AddProduction_Call struct {
	*mock.Call
}

// AddProduction is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - baseID uuid.UUID
//   - itemName string
//   - limit int
func (_e *MockRepository_Expecter) AddProduction(ctx interface{}, o interface{}, baseID interface{}, itemName interface{}, limit interface{}) *MockRepository_AddProduction_Call {
	return &MockRepository_AddProduction_Call{Call: _e.mock.On("AddProduction", ctx, o, baseID, itemName, limit)}
}

func (_c *MockRepository_AddProduction_Call) Run(run func(ctx context.Context, o bases.Ownership, baseID uuid.UUID, itemName string, limit int)) *MockRepository_AddProduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_AddProduction_Call) Return(_a0 error) *MockRepository_AddProduction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddProduction_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID, string, int) error) *MockRepository_AddProduction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with given fields: ctx, o
func (_m *MockRepository) DeleteAll(ctx context.Context, o bases.Ownership) (int, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership) (int, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership) int); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
func (_e *MockRepository_Expecter) DeleteAll(ctx interface{}, o interface{}) *MockRepository_DeleteAll_Call {
	return &MockRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, o)}
}

func (_c *MockRepository_DeleteAll_Call) Run(run func(ctx context.Context, o bases.Ownership)) *MockRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership))
	})
	return _c
}

func (_c *MockRepository_DeleteAll_Call) Return(_a0 int, _a1 error) *MockRepository_DeleteAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DeleteAll_Call) RunAndReturn(run func(context.Context, bases.Ownership) (int, error)) *MockRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOne provides a mock function with given fields: ctx, o, baseID
func (_m *MockRepository) DeleteOne(ctx context.Context, o bases.Ownership, baseID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, o, baseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) (int, error)); ok {
		return rf(ctx, o, baseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) int); ok {
		r0 = rf(ctx, o, baseID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, uuid.UUID) error); ok {
		r1 = rf(ctx, o, baseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DeleteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOne'
type MockRepository_DeleteOne_Call struct {
	*mock.Call
}

// DeleteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - baseID uuid.UUID
func (_e *MockRepository_Expecter) DeleteOne(ctx interface{}, o interface{}, baseID interface{}) *MockRepository_DeleteOne_Call {
	return &MockRepository_DeleteOne_Call{Call: _e.mock.On("DeleteOne", ctx, o, baseID)}
}

func (_c *MockRepository_DeleteOne_Call) Run(run func(ctx context.Context, o bases.Ownership, baseID uuid.UUID)) *MockRepository_DeleteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_DeleteOne_Call) Return(_a0 int, _a1 error) *MockRepository_DeleteOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DeleteOne_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID) (int, error)) *MockRepository_DeleteOne_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, serverID, f, limit, offset
func (_m *MockRepository) List(ctx context.Context, serverID uuid.UUID, f bases.Filter, limit int, offset int) ([]bases.Base, int, error) {
	ret := _m.Called(ctx, serverID, f, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []bases.Base
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bases.Filter, int, int) ([]bases.Base, int, error)); ok {
		return rf(ctx, serverID, f, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bases.Filter, int, int) []bases.Base); ok {
		r0 = rf(ctx, serverID, f, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bases.Base)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bases.Filter, int, int) int); ok {
		r1 = rf(ctx, serverID, f, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, bases.Filter, int, int) error); ok {
		r2 = rf(ctx, serverID, f, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - f bases.Filter
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) List(ctx interface{}, serverID interface{}, f interface{}, limit interface{}, offset interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, serverID, f, limit, offset)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, serverID uuid.UUID, f bases.Filter, limit int, offset int)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bases.Filter), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(page []bases.Base, total int, err error) *MockRepository_List_Call {
	_c.Call.Return(page, total, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, bases.Filter, int, int) ([]bases.Base, int, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListExtractors provides a mock function with given fields: ctx, o, baseID
func (_m *MockRepository) ListExtractors(ctx context.Context, o bases.Ownership, baseID uuid.UUID) ([]bases.Extractor, error) {
	ret := _m.Called(ctx, o, baseID)

	if len(ret) == 0 {
		panic("no return value specified for ListExtractors")
	}

	var r0 []bases.Extractor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) ([]bases.Extractor, error)); ok {
		return rf(ctx, o, baseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) []bases.Extractor); ok {
		r0 = rf(ctx, o, baseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bases.Extractor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, uuid.UUID) error); ok {
		r1 = rf(ctx, o, baseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListExtractors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExtractors'
type MockRepository_ListExtractors_Call struct {
	*mock.Call
}

// ListExtractors is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - baseID uuid.UUID
func (_e *MockRepository_Expecter) ListExtractors(ctx interface{}, o interface{}, baseID interface{}) *MockRepository_ListExtractors_Call {
	return &MockRepository_ListExtractors_Call{Call: _e.mock.On("ListExtractors", ctx, o, baseID)}
}

func (_c *MockRepository_ListExtractors_Call) Run(run func(ctx context.Context, o bases.Ownership, baseID uuid.UUID)) *MockRepository_ListExtractors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListExtractors_Call) Return(_a0 []bases.Extractor, _a1 error) *MockRepository_ListExtractors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListExtractors_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID) ([]bases.Extractor, error)) *MockRepository_ListExtractors_Call {
	_c.Call.Return(run)
	return _c
}

// ListOwned provides a mock function with given fields: ctx, o, limit
func (_m *MockRepository) ListOwned(ctx context.Context, o bases.Ownership, limit int) ([]bases.Base, error) {
	ret := _m.Called(ctx, o, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListOwned")
	}

	var r0 []bases.Base
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, int) ([]bases.Base, error)); ok {
		return rf(ctx, o, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, int) []bases.Base); ok {
		r0 = rf(ctx, o, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bases.Base)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, int) error); ok {
		r1 = rf(ctx, o, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOwned'
type MockRepository_ListOwned_Call struct {
	*mock.Call
}

// ListOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - limit int
func (_e *MockRepository_Expecter) ListOwned(ctx interface{}, o interface{}, limit interface{}) *MockRepository_ListOwned_Call {
	return &MockRepository_ListOwned_Call{Call: _e.mock.On("ListOwned", ctx, o, limit)}
}

func (_c *MockRepository_ListOwned_Call) Run(run func(ctx context.Context, o bases.Ownership, limit int)) *MockRepository_ListOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_ListOwned_Call) Return(_a0 []bases.Base, _a1 error) *MockRepository_ListOwned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListOwned_Call) RunAndReturn(run func(context.Context, bases.Ownership, int) ([]bases.Base, error)) *MockRepository_ListOwned_Call {
	_c.Call.Return(run)
	return _c
}

// ListProductions provides a mock function with given fields: ctx, o, baseID
func (_m *MockRepository) ListProductions(ctx context.Context, o bases.Ownership, baseID uuid.UUID) ([]bases.Production, error) {
	ret := _m.Called(ctx, o, baseID)

	if len(ret) == 0 {
		panic("no return value specified for ListProductions")
	}

	var r0 []bases.Production
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) ([]bases.Production, error)); ok {
		return rf(ctx, o, baseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) []bases.Production); ok {
		r0 = rf(ctx, o, baseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bases.Production)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, uuid.UUID) error); ok {
		r1 = rf(ctx, o, baseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListProductions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductions'
type MockRepository_ListProductions_Call struct {
	*mock.Call
}

// ListProductions is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - baseID uuid.UUID
func (_e *MockRepository_Expecter) ListProductions(ctx interface{}, o interface{}, baseID interface{}) *MockRepository_ListProductions_Call {
	return &MockRepository_ListProductions_Call{Call: _e.mock.On("ListProductions", ctx, o, baseID)}
}

func (_c *MockRepository_ListProductions_Call) Run(run func(ctx context.Context, o bases.Ownership, baseID uuid.UUID)) *MockRepository_ListProductions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListProductions_Call) Return(_a0 []bases.Production, _a1 error) *MockRepository_ListProductions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListProductions_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID) ([]bases.Production, error)) *MockRepository_ListProductions_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, limit
func (_m *MockRepository) Register(ctx context.Context, in bases.RegisterInput, limit int) (uuid.UUID, error) {
	ret := _m.Called(ctx, in, limit)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.RegisterInput, int) (uuid.UUID, error)); ok {
		return rf(ctx, in, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.RegisterInput, int) uuid.UUID); ok {
		r0 = rf(ctx, in, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.RegisterInput, int) error); ok {
		r1 = rf(ctx, in, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in bases.RegisterInput
//   - limit int
func (_e *MockRepository_Expecter) Register(ctx interface{}, in interface{}, limit interface{}) *MockRepository_Register_Call {
	return &MockRepository_Register_Call{Call: _e.mock.On("Register", ctx, in, limit)}
}

func (_c *MockRepository_Register_Call) Run(run func(ctx context.Context, in bases.RegisterInput, limit int)) *MockRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.RegisterInput), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_Register_Call) Return(_a0 uuid.UUID, _a1 error) *MockRepository_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Register_Call) RunAndReturn(run func(context.Context, bases.RegisterInput, int) (uuid.UUID, error)) *MockRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveExtractor provides a mock function with given fields: ctx, o, extractorID
func (_m *MockRepository) RemoveExtractor(ctx context.Context, o bases.Ownership, extractorID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, o, extractorID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveExtractor")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) (int, error)); ok {
		return rf(ctx, o, extractorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) int); ok {
		r0 = rf(ctx, o, extractorID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, uuid.UUID) error); ok {
		r1 = rf(ctx, o, extractorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RemoveExtractor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveExtractor'
type MockRepository_RemoveExtractor_Call struct {
	*mock.Call
}

// RemoveExtractor is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - extractorID uuid.UUID
func (_e *MockRepository_Expecter) RemoveExtractor(ctx interface{}, o interface{}, extractorID interface{}) *MockRepository_RemoveExtractor_Call {
	return &MockRepository_RemoveExtractor_Call{Call: _e.mock.On("RemoveExtractor", ctx, o, extractorID)}
}

func (_c *MockRepository_RemoveExtractor_Call) Run(run func(ctx context.Context, o bases.Ownership, extractorID uuid.UUID)) *MockRepository_RemoveExtractor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RemoveExtractor_Call) Return(_a0 int, _a1 error) *MockRepository_RemoveExtractor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RemoveExtractor_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID) (int, error)) *MockRepository_RemoveExtractor_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduction provides a mock function with given fields: ctx, o, productionID
func (_m *MockRepository) RemoveProduction(ctx context.Context, o bases.Ownership, productionID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, o, productionID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduction")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) (int, error)); ok {
		return rf(ctx, o, productionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bases.Ownership, uuid.UUID) int); ok {
		r0 = rf(ctx, o, productionID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bases.Ownership, uuid.UUID) error); ok {
		r1 = rf(ctx, o, productionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RemoveProduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduction'
type MockRepository_RemoveProduction_Call struct {
	*mock.Call
}

// RemoveProduction is a helper method to define mock.On call
//   - ctx context.Context
//   - o bases.Ownership
//   - productionID uuid.UUID
func (_e *MockRepository_Expecter) RemoveProduction(ctx interface{}, o interface{}, productionID interface{}) *MockRepository_RemoveProduction_Call {
	return &MockRepository_RemoveProduction_Call{Call: _e.mock.On("RemoveProduction", ctx, o, productionID)}
}

func (_c *MockRepository_RemoveProduction_Call) Run(run func(ctx context.Context, o bases.Ownership, productionID uuid.UUID)) *MockRepository_RemoveProduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bases.Ownership), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RemoveProduction_Call) Return(_a0 int, _a1 error) *MockRepository_RemoveProduction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RemoveProduction_Call) RunAndReturn(run func(context.Context, bases.Ownership, uuid.UUID) (int, error)) *MockRepository_RemoveProduction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
