// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockReportsConfig is an autogenerated mock type for the ReportsConfig type
type MockReportsConfig struct {
	mock.Mock
}

type MockReportsConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportsConfig) EXPECT() *MockReportsConfig_Expecter {
	return &MockReportsConfig_Expecter{mock: &_m.Mock}
}

// ContractsReportsChannelID provides a mock function with given fields: ctx, serverID
func (_m *MockReportsConfig) ContractsReportsChannelID(ctx context.Context, serverID uuid.UUID) (string, bool) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ContractsReportsChannelID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, bool)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockReportsConfig_ContractsReportsChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractsReportsChannelID'
type MockReportsConfig_ContractsReportsChannelID_Call struct {
	*mock.Call
}

// ContractsReportsChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockReportsConfig_Expecter) ContractsReportsChannelID(ctx interface{}, serverID interface{}) *MockReportsConfig_ContractsReportsChannelID_Call {
	return &MockReportsConfig_ContractsReportsChannelID_Call{Call: _e.mock.On("ContractsReportsChannelID", ctx, serverID)}
}

func (_c *MockReportsConfig_ContractsReportsChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockReportsConfig_ContractsReportsChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReportsConfig_ContractsReportsChannelID_Call) Return(_a0 string, _a1 bool) *MockReportsConfig_ContractsReportsChannelID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportsConfig_ContractsReportsChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, bool)) *MockReportsConfig_ContractsReportsChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsReportsChannelID provides a mock function with given fields: ctx, serverID, channelID
func (_m *MockReportsConfig) SetContractsReportsChannelID(ctx context.Context, serverID uuid.UUID, channelID string) error {
	ret := _m.Called(ctx, serverID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsReportsChannelID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportsConfig_SetContractsReportsChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsReportsChannelID'
type MockReportsConfig_SetContractsReportsChannelID_Call struct {
	*mock.Call
}

// SetContractsReportsChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - channelID string
func (_e *MockReportsConfig_Expecter) SetContractsReportsChannelID(ctx interface{}, serverID interface{}, channelID interface{}) *MockReportsConfig_SetContractsReportsChannelID_Call {
	return &MockReportsConfig_SetContractsReportsChannelID_Call{Call: _e.mock.On("SetContractsReportsChannelID", ctx, serverID, channelID)}
}

func (_c *MockReportsConfig_SetContractsReportsChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, channelID string)) *MockReportsConfig_SetContractsReportsChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockReportsConfig_SetContractsReportsChannelID_Call) Return(_a0 error) *MockReportsConfig_SetContractsReportsChannelID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportsConfig_SetContractsReportsChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockReportsConfig_SetContractsReportsChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportsConfig creates a new instance of MockReportsConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportsConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportsConfig {
	mock := &MockReportsConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
