// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	uuid "github.com/google/uuid"
	contracts "github.com/kweezl/spacecraft-corporation/internal/features/contracts"
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddItemByID provides a mock function with given fields: ctx, serverID, contractID, itemName, gdid, gdVersion, aliases, qty, maxItems, actor
func (_m *MockRepository) AddItemByID(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, itemName string, gdid string, gdVersion string, aliases []string, qty int, maxItems int, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, itemName, gdid, gdVersion, aliases, qty, maxItems, actor)

	if len(ret) == 0 {
		panic("no return value specified for AddItemByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string, []string, int, int, string) error); ok {
		r0 = rf(ctx, serverID, contractID, itemName, gdid, gdVersion, aliases, qty, maxItems, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItemByID'
type MockRepository_AddItemByID_Call struct {
	*mock.Call
}

// AddItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - itemName string
//   - gdid string
//   - gdVersion string
//   - aliases []string
//   - qty int
//   - maxItems int
//   - actor string
func (_e *MockRepository_Expecter) AddItemByID(ctx interface{}, serverID interface{}, contractID interface{}, itemName interface{}, gdid interface{}, gdVersion interface{}, aliases interface{}, qty interface{}, maxItems interface{}, actor interface{}) *MockRepository_AddItemByID_Call {
	return &MockRepository_AddItemByID_Call{Call: _e.mock.On("AddItemByID", ctx, serverID, contractID, itemName, gdid, gdVersion, aliases, qty, maxItems, actor)}
}

func (_c *MockRepository_AddItemByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, itemName string, gdid string, gdVersion string, aliases []string, qty int, maxItems int, actor string)) *MockRepository_AddItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(string), args[6].([]string), args[7].(int), args[8].(int), args[9].(string))
	})
	return _c
}

func (_c *MockRepository_AddItemByID_Call) Return(_a0 error) *MockRepository_AddItemByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, string, []string, int, int, string) error) *MockRepository_AddItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// CancelByID provides a mock function with given fields: ctx, serverID, contractID, actor
func (_m *MockRepository) CancelByID(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, actor)

	if len(ret) == 0 {
		panic("no return value specified for CancelByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, contractID, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CancelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelByID'
type MockRepository_CancelByID_Call struct {
	*mock.Call
}

// CancelByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - actor string
func (_e *MockRepository_Expecter) CancelByID(ctx interface{}, serverID interface{}, contractID interface{}, actor interface{}) *MockRepository_CancelByID_Call {
	return &MockRepository_CancelByID_Call{Call: _e.mock.On("CancelByID", ctx, serverID, contractID, actor)}
}

func (_c *MockRepository_CancelByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, actor string)) *MockRepository_CancelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_CancelByID_Call) Return(_a0 error) *MockRepository_CancelByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CancelByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockRepository_CancelByID_Call {
	_c.Call.Return(run)
	return _c
}

// Counts provides a mock function with given fields: ctx, serverID
func (_m *MockRepository) Counts(ctx context.Context, serverID uuid.UUID) (contracts.Counts, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Counts")
	}

	var r0 contracts.Counts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contracts.Counts, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) contracts.Counts); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(contracts.Counts)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Counts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counts'
type MockRepository_Counts_Call struct {
	*mock.Call
}

// Counts is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockRepository_Expecter) Counts(ctx interface{}, serverID interface{}) *MockRepository_Counts_Call {
	return &MockRepository_Counts_Call{Call: _e.mock.On("Counts", ctx, serverID)}
}

func (_c *MockRepository_Counts_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockRepository_Counts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Counts_Call) Return(_a0 contracts.Counts, _a1 error) *MockRepository_Counts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Counts_Call) RunAndReturn(run func(context.Context, uuid.UUID) (contracts.Counts, error)) *MockRepository_Counts_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockRepository) Create(ctx context.Context, in contracts.CreateInput) (uuid.UUID, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.CreateInput) (uuid.UUID, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.CreateInput) uuid.UUID); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in contracts.CreateInput
func (_e *MockRepository_Expecter) Create(ctx interface{}, in interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, in contracts.CreateInput)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.CreateInput))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, contracts.CreateInput) (uuid.UUID, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deliver provides a mock function with given fields: ctx, serverID, threadID, itemName, userID, qty
func (_m *MockRepository) Deliver(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int) (bool, error) {
	ret := _m.Called(ctx, serverID, threadID, itemName, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Deliver")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (bool, error)); ok {
		return rf(ctx, serverID, threadID, itemName, userID, qty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) bool); ok {
		r0 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Deliver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deliver'
type MockRepository_Deliver_Call struct {
	*mock.Call
}

// Deliver is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Deliver(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, userID interface{}, qty interface{}) *MockRepository_Deliver_Call {
	return &MockRepository_Deliver_Call{Call: _e.mock.On("Deliver", ctx, serverID, threadID, itemName, userID, qty)}
}

func (_c *MockRepository_Deliver_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int)) *MockRepository_Deliver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Deliver_Call) Return(complete bool, err error) *MockRepository_Deliver_Call {
	_c.Call.Return(complete, err)
	return _c
}

func (_c *MockRepository_Deliver_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) (bool, error)) *MockRepository_Deliver_Call {
	_c.Call.Return(run)
	return _c
}

// DeliverByItem provides a mock function with given fields: ctx, serverID, itemID, targetUserID, qty, actor
func (_m *MockRepository) DeliverByItem(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, qty int, actor string) (uuid.UUID, bool, error) {
	ret := _m.Called(ctx, serverID, itemID, targetUserID, qty, actor)

	if len(ret) == 0 {
		panic("no return value specified for DeliverByItem")
	}

	var r0 uuid.UUID
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, bool, error)); ok {
		return rf(ctx, serverID, itemID, targetUserID, qty, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, targetUserID, qty, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) bool); ok {
		r1 = rf(ctx, serverID, itemID, targetUserID, qty, actor)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) error); ok {
		r2 = rf(ctx, serverID, itemID, targetUserID, qty, actor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_DeliverByItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeliverByItem'
type MockRepository_DeliverByItem_Call struct {
	*mock.Call
}

// DeliverByItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - targetUserID string
//   - qty int
//   - actor string
func (_e *MockRepository_Expecter) DeliverByItem(ctx interface{}, serverID interface{}, itemID interface{}, targetUserID interface{}, qty interface{}, actor interface{}) *MockRepository_DeliverByItem_Call {
	return &MockRepository_DeliverByItem_Call{Call: _e.mock.On("DeliverByItem", ctx, serverID, itemID, targetUserID, qty, actor)}
}

func (_c *MockRepository_DeliverByItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, qty int, actor string)) *MockRepository_DeliverByItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_DeliverByItem_Call) Return(cid uuid.UUID, complete bool, err error) *MockRepository_DeliverByItem_Call {
	_c.Call.Return(cid, complete, err)
	return _c
}

func (_c *MockRepository_DeliverByItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, bool, error)) *MockRepository_DeliverByItem_Call {
	_c.Call.Return(run)
	return _c
}

// DueContracts provides a mock function with given fields: ctx, now, limit
func (_m *MockRepository) DueContracts(ctx context.Context, now time.Time, limit int) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for DueContracts")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]uuid.UUID, error)); ok {
		return rf(ctx, now, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []uuid.UUID); ok {
		r0 = rf(ctx, now, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DueContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DueContracts'
type MockRepository_DueContracts_Call struct {
	*mock.Call
}

// DueContracts is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int
func (_e *MockRepository_Expecter) DueContracts(ctx interface{}, now interface{}, limit interface{}) *MockRepository_DueContracts_Call {
	return &MockRepository_DueContracts_Call{Call: _e.mock.On("DueContracts", ctx, now, limit)}
}

func (_c *MockRepository_DueContracts_Call) Run(run func(ctx context.Context, now time.Time, limit int)) *MockRepository_DueContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_DueContracts_Call) Return(_a0 []uuid.UUID, _a1 error) *MockRepository_DueContracts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DueContracts_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]uuid.UUID, error)) *MockRepository_DueContracts_Call {
	_c.Call.Return(run)
	return _c
}

// KindByID provides a mock function with given fields: ctx, serverID, contractID
func (_m *MockRepository) KindByID(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID) (contracts.Kind, error) {
	ret := _m.Called(ctx, serverID, contractID)

	if len(ret) == 0 {
		panic("no return value specified for KindByID")
	}

	var r0 contracts.Kind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.Kind, error)); ok {
		return rf(ctx, serverID, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.Kind); ok {
		r0 = rf(ctx, serverID, contractID)
	} else {
		r0 = ret.Get(0).(contracts.Kind)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_KindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KindByID'
type MockRepository_KindByID_Call struct {
	*mock.Call
}

// KindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) KindByID(ctx interface{}, serverID interface{}, contractID interface{}) *MockRepository_KindByID_Call {
	return &MockRepository_KindByID_Call{Call: _e.mock.On("KindByID", ctx, serverID, contractID)}
}

func (_c *MockRepository_KindByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID)) *MockRepository_KindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_KindByID_Call) Return(_a0 contracts.Kind, _a1 error) *MockRepository_KindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_KindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.Kind, error)) *MockRepository_KindByID_Call {
	_c.Call.Return(run)
	return _c
}

// KindByItem provides a mock function with given fields: ctx, serverID, itemID
func (_m *MockRepository) KindByItem(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID) (contracts.Kind, error) {
	ret := _m.Called(ctx, serverID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for KindByItem")
	}

	var r0 contracts.Kind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.Kind, error)); ok {
		return rf(ctx, serverID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.Kind); ok {
		r0 = rf(ctx, serverID, itemID)
	} else {
		r0 = ret.Get(0).(contracts.Kind)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_KindByItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KindByItem'
type MockRepository_KindByItem_Call struct {
	*mock.Call
}

// KindByItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockRepository_Expecter) KindByItem(ctx interface{}, serverID interface{}, itemID interface{}) *MockRepository_KindByItem_Call {
	return &MockRepository_KindByItem_Call{Call: _e.mock.On("KindByItem", ctx, serverID, itemID)}
}

func (_c *MockRepository_KindByItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID)) *MockRepository_KindByItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_KindByItem_Call) Return(_a0 contracts.Kind, _a1 error) *MockRepository_KindByItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_KindByItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.Kind, error)) *MockRepository_KindByItem_Call {
	_c.Call.Return(run)
	return _c
}

// LinkItemGDID provides a mock function with given fields: ctx, serverID, itemID, gdid, gdVersion, aliases, actor
func (_m *MockRepository) LinkItemGDID(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, gdid string, gdVersion string, aliases []string, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, itemID, gdid, gdVersion, aliases, actor)

	if len(ret) == 0 {
		panic("no return value specified for LinkItemGDID")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, []string, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, itemID, gdid, gdVersion, aliases, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, []string, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, gdid, gdVersion, aliases, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, []string, string) error); ok {
		r1 = rf(ctx, serverID, itemID, gdid, gdVersion, aliases, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_LinkItemGDID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkItemGDID'
type MockRepository_LinkItemGDID_Call struct {
	*mock.Call
}

// LinkItemGDID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - gdid string
//   - gdVersion string
//   - aliases []string
//   - actor string
func (_e *MockRepository_Expecter) LinkItemGDID(ctx interface{}, serverID interface{}, itemID interface{}, gdid interface{}, gdVersion interface{}, aliases interface{}, actor interface{}) *MockRepository_LinkItemGDID_Call {
	return &MockRepository_LinkItemGDID_Call{Call: _e.mock.On("LinkItemGDID", ctx, serverID, itemID, gdid, gdVersion, aliases, actor)}
}

func (_c *MockRepository_LinkItemGDID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, gdid string, gdVersion string, aliases []string, actor string)) *MockRepository_LinkItemGDID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].([]string), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_LinkItemGDID_Call) Return(cid uuid.UUID, err error) *MockRepository_LinkItemGDID_Call {
	_c.Call.Return(cid, err)
	return _c
}

func (_c *MockRepository_LinkItemGDID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, []string, string) (uuid.UUID, error)) *MockRepository_LinkItemGDID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, serverID, statuses, limit, offset
func (_m *MockRepository) List(ctx context.Context, serverID uuid.UUID, statuses []contracts.Status, limit int, offset int) ([]contracts.ListEntry, int, error) {
	ret := _m.Called(ctx, serverID, statuses, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []contracts.ListEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []contracts.Status, int, int) ([]contracts.ListEntry, int, error)); ok {
		return rf(ctx, serverID, statuses, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []contracts.Status, int, int) []contracts.ListEntry); ok {
		r0 = rf(ctx, serverID, statuses, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.ListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []contracts.Status, int, int) int); ok {
		r1 = rf(ctx, serverID, statuses, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, []contracts.Status, int, int) error); ok {
		r2 = rf(ctx, serverID, statuses, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - statuses []contracts.Status
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) List(ctx interface{}, serverID interface{}, statuses interface{}, limit interface{}, offset interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, serverID, statuses, limit, offset)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, serverID uuid.UUID, statuses []contracts.Status, limit int, offset int)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]contracts.Status), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(page []contracts.ListEntry, total int, err error) *MockRepository_List_Call {
	_c.Call.Return(page, total, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, []contracts.Status, int, int) ([]contracts.ListEntry, int, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkExpired provides a mock function with given fields: ctx, id, now
func (_m *MockRepository) MarkExpired(ctx context.Context, id uuid.UUID, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkExpired")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MarkExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkExpired'
type MockRepository_MarkExpired_Call struct {
	*mock.Call
}

// MarkExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkExpired(ctx interface{}, id interface{}, now interface{}) *MockRepository_MarkExpired_Call {
	return &MockRepository_MarkExpired_Call{Call: _e.mock.On("MarkExpired", ctx, id, now)}
}

func (_c *MockRepository_MarkExpired_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *MockRepository_MarkExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_MarkExpired_Call) Return(_a0 bool, _a1 error) *MockRepository_MarkExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MarkExpired_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRepository_MarkExpired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotified provides a mock function with given fields: ctx, id, now
func (_m *MockRepository) MarkNotified(ctx context.Context, id uuid.UUID, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotified")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MarkNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotified'
type MockRepository_MarkNotified_Call struct {
	*mock.Call
}

// MarkNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkNotified(ctx interface{}, id interface{}, now interface{}) *MockRepository_MarkNotified_Call {
	return &MockRepository_MarkNotified_Call{Call: _e.mock.On("MarkNotified", ctx, id, now)}
}

func (_c *MockRepository_MarkNotified_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *MockRepository_MarkNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_MarkNotified_Call) Return(_a0 bool, _a1 error) *MockRepository_MarkNotified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MarkNotified_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRepository_MarkNotified_Call {
	_c.Call.Return(run)
	return _c
}

// MemberOutstanding provides a mock function with given fields: ctx, serverID, threadID, userID
func (_m *MockRepository) MemberOutstanding(ctx context.Context, serverID uuid.UUID, threadID string, userID string) ([]contracts.MemberItem, error) {
	ret := _m.Called(ctx, serverID, threadID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MemberOutstanding")
	}

	var r0 []contracts.MemberItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]contracts.MemberItem, error)); ok {
		return rf(ctx, serverID, threadID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []contracts.MemberItem); ok {
		r0 = rf(ctx, serverID, threadID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.MemberItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, serverID, threadID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MemberOutstanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberOutstanding'
type MockRepository_MemberOutstanding_Call struct {
	*mock.Call
}

// MemberOutstanding is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - userID string
func (_e *MockRepository_Expecter) MemberOutstanding(ctx interface{}, serverID interface{}, threadID interface{}, userID interface{}) *MockRepository_MemberOutstanding_Call {
	return &MockRepository_MemberOutstanding_Call{Call: _e.mock.On("MemberOutstanding", ctx, serverID, threadID, userID)}
}

func (_c *MockRepository_MemberOutstanding_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, userID string)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) Return(_a0 []contracts.MemberItem, _a1 error) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]contracts.MemberItem, error)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyDue provides a mock function with given fields: ctx, now, within, limit
func (_m *MockRepository) NotifyDue(ctx context.Context, now time.Time, within time.Duration, limit int) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, now, within, limit)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDue")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) ([]uuid.UUID, error)); ok {
		return rf(ctx, now, within, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) []uuid.UUID); ok {
		r0 = rf(ctx, now, within, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Duration, int) error); ok {
		r1 = rf(ctx, now, within, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_NotifyDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDue'
type MockRepository_NotifyDue_Call struct {
	*mock.Call
}

// NotifyDue is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - within time.Duration
//   - limit int
func (_e *MockRepository_Expecter) NotifyDue(ctx interface{}, now interface{}, within interface{}, limit interface{}) *MockRepository_NotifyDue_Call {
	return &MockRepository_NotifyDue_Call{Call: _e.mock.On("NotifyDue", ctx, now, within, limit)}
}

func (_c *MockRepository_NotifyDue_Call) Run(run func(ctx context.Context, now time.Time, within time.Duration, limit int)) *MockRepository_NotifyDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Duration), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_NotifyDue_Call) Return(_a0 []uuid.UUID, _a1 error) *MockRepository_NotifyDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_NotifyDue_Call) RunAndReturn(run func(context.Context, time.Time, time.Duration, int) ([]uuid.UUID, error)) *MockRepository_NotifyDue_Call {
	_c.Call.Return(run)
	return _c
}

// OutstandingParticipantUserIDs provides a mock function with given fields: ctx, contractID
func (_m *MockRepository) OutstandingParticipantUserIDs(ctx context.Context, contractID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for OutstandingParticipantUserIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, contractID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_OutstandingParticipantUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutstandingParticipantUserIDs'
type MockRepository_OutstandingParticipantUserIDs_Call struct {
	*mock.Call
}

// OutstandingParticipantUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) OutstandingParticipantUserIDs(ctx interface{}, contractID interface{}) *MockRepository_OutstandingParticipantUserIDs_Call {
	return &MockRepository_OutstandingParticipantUserIDs_Call{Call: _e.mock.On("OutstandingParticipantUserIDs", ctx, contractID)}
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) Run(run func(ctx context.Context, contractID uuid.UUID)) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) Return(_a0 []string, _a1 error) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Participate provides a mock function with given fields: ctx, serverID, threadID, itemName, userID, qty
func (_m *MockRepository) Participate(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int) error {
	ret := _m.Called(ctx, serverID, threadID, itemName, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Participate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r0 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Participate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Participate'
type MockRepository_Participate_Call struct {
	*mock.Call
}

// Participate is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Participate(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, userID interface{}, qty interface{}) *MockRepository_Participate_Call {
	return &MockRepository_Participate_Call{Call: _e.mock.On("Participate", ctx, serverID, threadID, itemName, userID, qty)}
}

func (_c *MockRepository_Participate_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int)) *MockRepository_Participate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Participate_Call) Return(_a0 error) *MockRepository_Participate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Participate_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) error) *MockRepository_Participate_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with given fields: ctx, serverID, threadID
func (_m *MockRepository) Progress(ctx context.Context, serverID uuid.UUID, threadID string) (contracts.Progress, error) {
	ret := _m.Called(ctx, serverID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (contracts.Progress, error)); ok {
		return rf(ctx, serverID, threadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) contracts.Progress); ok {
		r0 = rf(ctx, serverID, threadID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, serverID, threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockRepository_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) Progress(ctx interface{}, serverID interface{}, threadID interface{}) *MockRepository_Progress_Call {
	return &MockRepository_Progress_Call{Call: _e.mock.On("Progress", ctx, serverID, threadID)}
}

func (_c *MockRepository_Progress_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string)) *MockRepository_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Progress_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_Progress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Progress_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (contracts.Progress, error)) *MockRepository_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByID provides a mock function with given fields: ctx, contractID
func (_m *MockRepository) ProgressByID(ctx context.Context, contractID uuid.UUID) (contracts.Progress, error) {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByID")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contracts.Progress, error)); ok {
		return rf(ctx, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) contracts.Progress); ok {
		r0 = rf(ctx, contractID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByID'
type MockRepository_ProgressByID_Call struct {
	*mock.Call
}

// ProgressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByID(ctx interface{}, contractID interface{}) *MockRepository_ProgressByID_Call {
	return &MockRepository_ProgressByID_Call{Call: _e.mock.On("ProgressByID", ctx, contractID)}
}

func (_c *MockRepository_ProgressByID_Call) Run(run func(ctx context.Context, contractID uuid.UUID)) *MockRepository_ProgressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByID_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_ProgressByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (contracts.Progress, error)) *MockRepository_ProgressByID_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByIDScoped provides a mock function with given fields: ctx, serverID, contractID
func (_m *MockRepository) ProgressByIDScoped(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID) (contracts.Progress, error) {
	ret := _m.Called(ctx, serverID, contractID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByIDScoped")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.Progress, error)); ok {
		return rf(ctx, serverID, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.Progress); ok {
		r0 = rf(ctx, serverID, contractID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByIDScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByIDScoped'
type MockRepository_ProgressByIDScoped_Call struct {
	*mock.Call
}

// ProgressByIDScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByIDScoped(ctx interface{}, serverID interface{}, contractID interface{}) *MockRepository_ProgressByIDScoped_Call {
	return &MockRepository_ProgressByIDScoped_Call{Call: _e.mock.On("ProgressByIDScoped", ctx, serverID, contractID)}
}

func (_c *MockRepository_ProgressByIDScoped_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID)) *MockRepository_ProgressByIDScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByIDScoped_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_ProgressByIDScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByIDScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.Progress, error)) *MockRepository_ProgressByIDScoped_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByItemScoped provides a mock function with given fields: ctx, serverID, itemID
func (_m *MockRepository) ProgressByItemScoped(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID) (contracts.Progress, error) {
	ret := _m.Called(ctx, serverID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByItemScoped")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.Progress, error)); ok {
		return rf(ctx, serverID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.Progress); ok {
		r0 = rf(ctx, serverID, itemID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByItemScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByItemScoped'
type MockRepository_ProgressByItemScoped_Call struct {
	*mock.Call
}

// ProgressByItemScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByItemScoped(ctx interface{}, serverID interface{}, itemID interface{}) *MockRepository_ProgressByItemScoped_Call {
	return &MockRepository_ProgressByItemScoped_Call{Call: _e.mock.On("ProgressByItemScoped", ctx, serverID, itemID)}
}

func (_c *MockRepository_ProgressByItemScoped_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID)) *MockRepository_ProgressByItemScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByItemScoped_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_ProgressByItemScoped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByItemScoped_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.Progress, error)) *MockRepository_ProgressByItemScoped_Call {
	_c.Call.Return(run)
	return _c
}

// RecreatePost provides a mock function with given fields: ctx, contractID
func (_m *MockRepository) RecreatePost(ctx context.Context, contractID uuid.UUID) error {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for RecreatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, contractID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RecreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecreatePost'
type MockRepository_RecreatePost_Call struct {
	*mock.Call
}

// RecreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) RecreatePost(ctx interface{}, contractID interface{}) *MockRepository_RecreatePost_Call {
	return &MockRepository_RecreatePost_Call{Call: _e.mock.On("RecreatePost", ctx, contractID)}
}

func (_c *MockRepository_RecreatePost_Call) Run(run func(ctx context.Context, contractID uuid.UUID)) *MockRepository_RecreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RecreatePost_Call) Return(_a0 error) *MockRepository_RecreatePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RecreatePost_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_RecreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, serverID, threadID, itemName, targetUserID, qty, actor
func (_m *MockRepository) Release(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, targetUserID string, qty int, actor string) error {
	ret := _m.Called(ctx, serverID, threadID, itemName, targetUserID, qty, actor)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int, string) error); ok {
		r0 = rf(ctx, serverID, threadID, itemName, targetUserID, qty, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - targetUserID string
//   - qty int
//   - actor string
func (_e *MockRepository_Expecter) Release(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, targetUserID interface{}, qty interface{}, actor interface{}) *MockRepository_Release_Call {
	return &MockRepository_Release_Call{Call: _e.mock.On("Release", ctx, serverID, threadID, itemName, targetUserID, qty, actor)}
}

func (_c *MockRepository_Release_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, targetUserID string, qty int, actor string)) *MockRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_Release_Call) Return(_a0 error) *MockRepository_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Release_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int, string) error) *MockRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItemByID provides a mock function with given fields: ctx, serverID, itemID, actor
func (_m *MockRepository) RemoveItemByID(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, actor string) (uuid.UUID, int, error) {
	ret := _m.Called(ctx, serverID, itemID, actor)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItemByID")
	}

	var r0 uuid.UUID
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, int, error)); ok {
		return rf(ctx, serverID, itemID, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) int); ok {
		r1 = rf(ctx, serverID, itemID, actor)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r2 = rf(ctx, serverID, itemID, actor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_RemoveItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItemByID'
type MockRepository_RemoveItemByID_Call struct {
	*mock.Call
}

// RemoveItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - actor string
func (_e *MockRepository_Expecter) RemoveItemByID(ctx interface{}, serverID interface{}, itemID interface{}, actor interface{}) *MockRepository_RemoveItemByID_Call {
	return &MockRepository_RemoveItemByID_Call{Call: _e.mock.On("RemoveItemByID", ctx, serverID, itemID, actor)}
}

func (_c *MockRepository_RemoveItemByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, actor string)) *MockRepository_RemoveItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_RemoveItemByID_Call) Return(cid uuid.UUID, cleared int, err error) *MockRepository_RemoveItemByID_Call {
	_c.Call.Return(cid, cleared, err)
	return _c
}

func (_c *MockRepository_RemoveItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, int, error)) *MockRepository_RemoveItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReservation provides a mock function with given fields: ctx, serverID, itemID, targetUserID, actor
func (_m *MockRepository) RemoveReservation(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, itemID, targetUserID, actor)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReservation")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, itemID, targetUserID, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, targetUserID, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, serverID, itemID, targetUserID, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RemoveReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReservation'
type MockRepository_RemoveReservation_Call struct {
	*mock.Call
}

// RemoveReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - targetUserID string
//   - actor string
func (_e *MockRepository_Expecter) RemoveReservation(ctx interface{}, serverID interface{}, itemID interface{}, targetUserID interface{}, actor interface{}) *MockRepository_RemoveReservation_Call {
	return &MockRepository_RemoveReservation_Call{Call: _e.mock.On("RemoveReservation", ctx, serverID, itemID, targetUserID, actor)}
}

func (_c *MockRepository_RemoveReservation_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, actor string)) *MockRepository_RemoveReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockRepository_RemoveReservation_Call) Return(cid uuid.UUID, err error) *MockRepository_RemoveReservation_Call {
	_c.Call.Return(cid, err)
	return _c
}

func (_c *MockRepository_RemoveReservation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (uuid.UUID, error)) *MockRepository_RemoveReservation_Call {
	_c.Call.Return(run)
	return _c
}

// Republish provides a mock function with given fields: ctx, serverID, contractID
func (_m *MockRepository) Republish(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID) (contracts.RepublishAction, error) {
	ret := _m.Called(ctx, serverID, contractID)

	if len(ret) == 0 {
		panic("no return value specified for Republish")
	}

	var r0 contracts.RepublishAction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.RepublishAction, error)); ok {
		return rf(ctx, serverID, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.RepublishAction); ok {
		r0 = rf(ctx, serverID, contractID)
	} else {
		r0 = ret.Get(0).(contracts.RepublishAction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Republish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Republish'
type MockRepository_Republish_Call struct {
	*mock.Call
}

// Republish is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) Republish(ctx interface{}, serverID interface{}, contractID interface{}) *MockRepository_Republish_Call {
	return &MockRepository_Republish_Call{Call: _e.mock.On("Republish", ctx, serverID, contractID)}
}

func (_c *MockRepository_Republish_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID)) *MockRepository_Republish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Republish_Call) Return(_a0 contracts.RepublishAction, _a1 error) *MockRepository_Republish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Republish_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.RepublishAction, error)) *MockRepository_Republish_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeadline provides a mock function with given fields: ctx, serverID, contractID, deadline, actor
func (_m *MockRepository) SetDeadline(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, deadline *time.Time, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, deadline, actor)

	if len(ret) == 0 {
		panic("no return value specified for SetDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *time.Time, string) error); ok {
		r0 = rf(ctx, serverID, contractID, deadline, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeadline'
type MockRepository_SetDeadline_Call struct {
	*mock.Call
}

// SetDeadline is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - deadline *time.Time
//   - actor string
func (_e *MockRepository_Expecter) SetDeadline(ctx interface{}, serverID interface{}, contractID interface{}, deadline interface{}, actor interface{}) *MockRepository_SetDeadline_Call {
	return &MockRepository_SetDeadline_Call{Call: _e.mock.On("SetDeadline", ctx, serverID, contractID, deadline, actor)}
}

func (_c *MockRepository_SetDeadline_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, deadline *time.Time, actor string)) *MockRepository_SetDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*time.Time), args[4].(string))
	})
	return _c
}

func (_c *MockRepository_SetDeadline_Call) Return(_a0 error) *MockRepository_SetDeadline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetDeadline_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *time.Time, string) error) *MockRepository_SetDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeliveryLocation provides a mock function with given fields: ctx, serverID, contractID, gdid, gdVersion, actor
func (_m *MockRepository) SetDeliveryLocation(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, gdid string, gdVersion string, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, gdid, gdVersion, actor)

	if len(ret) == 0 {
		panic("no return value specified for SetDeliveryLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, serverID, contractID, gdid, gdVersion, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetDeliveryLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeliveryLocation'
type MockRepository_SetDeliveryLocation_Call struct {
	*mock.Call
}

// SetDeliveryLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - gdid string
//   - gdVersion string
//   - actor string
func (_e *MockRepository_Expecter) SetDeliveryLocation(ctx interface{}, serverID interface{}, contractID interface{}, gdid interface{}, gdVersion interface{}, actor interface{}) *MockRepository_SetDeliveryLocation_Call {
	return &MockRepository_SetDeliveryLocation_Call{Call: _e.mock.On("SetDeliveryLocation", ctx, serverID, contractID, gdid, gdVersion, actor)}
}

func (_c *MockRepository_SetDeliveryLocation_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, gdid string, gdVersion string, actor string)) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_SetDeliveryLocation_Call) Return(_a0 error) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetDeliveryLocation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Return(run)
	return _c
}

// SetReservationByItem provides a mock function with given fields: ctx, serverID, itemID, targetUserID, newReserved, actor
func (_m *MockRepository) SetReservationByItem(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, newReserved int, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, itemID, targetUserID, newReserved, actor)

	if len(ret) == 0 {
		panic("no return value specified for SetReservationByItem")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, itemID, targetUserID, newReserved, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, targetUserID, newReserved, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) error); ok {
		r1 = rf(ctx, serverID, itemID, targetUserID, newReserved, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SetReservationByItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReservationByItem'
type MockRepository_SetReservationByItem_Call struct {
	*mock.Call
}

// SetReservationByItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - targetUserID string
//   - newReserved int
//   - actor string
func (_e *MockRepository_Expecter) SetReservationByItem(ctx interface{}, serverID interface{}, itemID interface{}, targetUserID interface{}, newReserved interface{}, actor interface{}) *MockRepository_SetReservationByItem_Call {
	return &MockRepository_SetReservationByItem_Call{Call: _e.mock.On("SetReservationByItem", ctx, serverID, itemID, targetUserID, newReserved, actor)}
}

func (_c *MockRepository_SetReservationByItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, targetUserID string, newReserved int, actor string)) *MockRepository_SetReservationByItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_SetReservationByItem_Call) Return(cid uuid.UUID, err error) *MockRepository_SetReservationByItem_Call {
	_c.Call.Return(cid, err)
	return _c
}

func (_c *MockRepository_SetReservationByItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, error)) *MockRepository_SetReservationByItem_Call {
	_c.Call.Return(run)
	return _c
}

// SetThreadID provides a mock function with given fields: ctx, contractID, threadID
func (_m *MockRepository) SetThreadID(ctx context.Context, contractID uuid.UUID, threadID string) error {
	ret := _m.Called(ctx, contractID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for SetThreadID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, contractID, threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThreadID'
type MockRepository_SetThreadID_Call struct {
	*mock.Call
}

// SetThreadID is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) SetThreadID(ctx interface{}, contractID interface{}, threadID interface{}) *MockRepository_SetThreadID_Call {
	return &MockRepository_SetThreadID_Call{Call: _e.mock.On("SetThreadID", ctx, contractID, threadID)}
}

func (_c *MockRepository_SetThreadID_Call) Run(run func(ctx context.Context, contractID uuid.UUID, threadID string)) *MockRepository_SetThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetThreadID_Call) Return(_a0 error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetThreadID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDetails provides a mock function with given fields: ctx, serverID, contractID, title, description, actor
func (_m *MockRepository) UpdateDetails(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, title string, description string, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, title, description, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, serverID, contractID, title, description, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDetails'
type MockRepository_UpdateDetails_Call struct {
	*mock.Call
}

// UpdateDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - title string
//   - description string
//   - actor string
func (_e *MockRepository_Expecter) UpdateDetails(ctx interface{}, serverID interface{}, contractID interface{}, title interface{}, description interface{}, actor interface{}) *MockRepository_UpdateDetails_Call {
	return &MockRepository_UpdateDetails_Call{Call: _e.mock.On("UpdateDetails", ctx, serverID, contractID, title, description, actor)}
}

func (_c *MockRepository_UpdateDetails_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, title string, description string, actor string)) *MockRepository_UpdateDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateDetails_Call) Return(_a0 error) *MockRepository_UpdateDetails_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateDetails_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error) *MockRepository_UpdateDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, serverID, itemID, newName, newQty, actor
func (_m *MockRepository) UpdateItem(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, newName string, newQty int, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, itemID, newName, newQty, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, itemID, newName, newQty, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, itemID, newName, newQty, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int, string) error); ok {
		r1 = rf(ctx, serverID, itemID, newName, newQty, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - itemID uuid.UUID
//   - newName string
//   - newQty int
//   - actor string
func (_e *MockRepository_Expecter) UpdateItem(ctx interface{}, serverID interface{}, itemID interface{}, newName interface{}, newQty interface{}, actor interface{}) *MockRepository_UpdateItem_Call {
	return &MockRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, serverID, itemID, newName, newQty, actor)}
}

func (_c *MockRepository_UpdateItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, itemID uuid.UUID, newName string, newQty int, actor string)) *MockRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateItem_Call) Return(cid uuid.UUID, err error) *MockRepository_UpdateItem_Call {
	_c.Call.Return(cid, err)
	return _c
}

func (_c *MockRepository_UpdateItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int, string) (uuid.UUID, error)) *MockRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRewards provides a mock function with given fields: ctx, serverID, contractID, credits, reputation, licencePoints, actor
func (_m *MockRepository) UpdateRewards(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, credits *decimal.Decimal, reputation *int, licencePoints *int, actor string) error {
	ret := _m.Called(ctx, serverID, contractID, credits, reputation, licencePoints, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRewards")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *decimal.Decimal, *int, *int, string) error); ok {
		r0 = rf(ctx, serverID, contractID, credits, reputation, licencePoints, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateRewards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRewards'
type MockRepository_UpdateRewards_Call struct {
	*mock.Call
}

// UpdateRewards is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - contractID uuid.UUID
//   - credits *decimal.Decimal
//   - reputation *int
//   - licencePoints *int
//   - actor string
func (_e *MockRepository_Expecter) UpdateRewards(ctx interface{}, serverID interface{}, contractID interface{}, credits interface{}, reputation interface{}, licencePoints interface{}, actor interface{}) *MockRepository_UpdateRewards_Call {
	return &MockRepository_UpdateRewards_Call{Call: _e.mock.On("UpdateRewards", ctx, serverID, contractID, credits, reputation, licencePoints, actor)}
}

func (_c *MockRepository_UpdateRewards_Call) Run(run func(ctx context.Context, serverID uuid.UUID, contractID uuid.UUID, credits *decimal.Decimal, reputation *int, licencePoints *int, actor string)) *MockRepository_UpdateRewards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*decimal.Decimal), args[4].(*int), args[5].(*int), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateRewards_Call) Return(_a0 error) *MockRepository_UpdateRewards_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateRewards_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *decimal.Decimal, *int, *int, string) error) *MockRepository_UpdateRewards_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
