// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	i18n "github.com/kweezl/spacecraft-corporation/internal/i18n"
	mock "github.com/stretchr/testify/mock"
)

// MockLangResolver is an autogenerated mock type for the LangResolver type
type MockLangResolver struct {
	mock.Mock
}

type MockLangResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLangResolver) EXPECT() *MockLangResolver_Expecter {
	return &MockLangResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, serverID
func (_m *MockLangResolver) Resolve(ctx context.Context, serverID uuid.UUID) (string, i18n.Language) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 i18n.Language
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, i18n.Language)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) i18n.Language); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(i18n.Language)
	}

	return r0, r1
}

// MockLangResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockLangResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockLangResolver_Expecter) Resolve(ctx interface{}, serverID interface{}) *MockLangResolver_Resolve_Call {
	return &MockLangResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, serverID)}
}

func (_c *MockLangResolver_Resolve_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockLangResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLangResolver_Resolve_Call) Return(theme string, lang i18n.Language) *MockLangResolver_Resolve_Call {
	_c.Call.Return(theme, lang)
	return _c
}

func (_c *MockLangResolver_Resolve_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, i18n.Language)) *MockLangResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLangResolver creates a new instance of MockLangResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLangResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLangResolver {
	mock := &MockLangResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
