// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockForumConfig is an autogenerated mock type for the ForumConfig type
type MockForumConfig struct {
	mock.Mock
}

type MockForumConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForumConfig) EXPECT() *MockForumConfig_Expecter {
	return &MockForumConfig_Expecter{mock: &_m.Mock}
}

// ContractsForumChannelID provides a mock function with given fields: ctx, serverID
func (_m *MockForumConfig) ContractsForumChannelID(ctx context.Context, serverID uuid.UUID) (string, bool) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ContractsForumChannelID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, bool)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockForumConfig_ContractsForumChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractsForumChannelID'
type MockForumConfig_ContractsForumChannelID_Call struct {
	*mock.Call
}

// ContractsForumChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockForumConfig_Expecter) ContractsForumChannelID(ctx interface{}, serverID interface{}) *MockForumConfig_ContractsForumChannelID_Call {
	return &MockForumConfig_ContractsForumChannelID_Call{Call: _e.mock.On("ContractsForumChannelID", ctx, serverID)}
}

func (_c *MockForumConfig_ContractsForumChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockForumConfig_ContractsForumChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockForumConfig_ContractsForumChannelID_Call) Return(_a0 string, _a1 bool) *MockForumConfig_ContractsForumChannelID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForumConfig_ContractsForumChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, bool)) *MockForumConfig_ContractsForumChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsForumChannelID provides a mock function with given fields: ctx, serverID, channelID
func (_m *MockForumConfig) SetContractsForumChannelID(ctx context.Context, serverID uuid.UUID, channelID string) error {
	ret := _m.Called(ctx, serverID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsForumChannelID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockForumConfig_SetContractsForumChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsForumChannelID'
type MockForumConfig_SetContractsForumChannelID_Call struct {
	*mock.Call
}

// SetContractsForumChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - channelID string
func (_e *MockForumConfig_Expecter) SetContractsForumChannelID(ctx interface{}, serverID interface{}, channelID interface{}) *MockForumConfig_SetContractsForumChannelID_Call {
	return &MockForumConfig_SetContractsForumChannelID_Call{Call: _e.mock.On("SetContractsForumChannelID", ctx, serverID, channelID)}
}

func (_c *MockForumConfig_SetContractsForumChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, channelID string)) *MockForumConfig_SetContractsForumChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockForumConfig_SetContractsForumChannelID_Call) Return(_a0 error) *MockForumConfig_SetContractsForumChannelID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockForumConfig_SetContractsForumChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockForumConfig_SetContractsForumChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockForumConfig creates a new instance of MockForumConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForumConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForumConfig {
	mock := &MockForumConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
