// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	discordgo "github.com/bwmarrin/discordgo"
	mock "github.com/stretchr/testify/mock"
)

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// ClosePost provides a mock function with given fields: threadID, embed
func (_m *MockGateway) ClosePost(threadID string, embed *discordgo.MessageEmbed) error {
	ret := _m.Called(threadID, embed)

	if len(ret) == 0 {
		panic("no return value specified for ClosePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *discordgo.MessageEmbed) error); ok {
		r0 = rf(threadID, embed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_ClosePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePost'
type MockGateway_ClosePost_Call struct {
	*mock.Call
}

// ClosePost is a helper method to define mock.On call
//   - threadID string
//   - embed *discordgo.MessageEmbed
func (_e *MockGateway_Expecter) ClosePost(threadID interface{}, embed interface{}) *MockGateway_ClosePost_Call {
	return &MockGateway_ClosePost_Call{Call: _e.mock.On("ClosePost", threadID, embed)}
}

func (_c *MockGateway_ClosePost_Call) Run(run func(threadID string, embed *discordgo.MessageEmbed)) *MockGateway_ClosePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*discordgo.MessageEmbed))
	})
	return _c
}

func (_c *MockGateway_ClosePost_Call) Return(_a0 error) *MockGateway_ClosePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_ClosePost_Call) RunAndReturn(run func(string, *discordgo.MessageEmbed) error) *MockGateway_ClosePost_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForumPost provides a mock function with given fields: channelID, name, embed
func (_m *MockGateway) CreateForumPost(channelID string, name string, embed *discordgo.MessageEmbed) (string, error) {
	ret := _m.Called(channelID, name, embed)

	if len(ret) == 0 {
		panic("no return value specified for CreateForumPost")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *discordgo.MessageEmbed) (string, error)); ok {
		return rf(channelID, name, embed)
	}
	if rf, ok := ret.Get(0).(func(string, string, *discordgo.MessageEmbed) string); ok {
		r0 = rf(channelID, name, embed)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, *discordgo.MessageEmbed) error); ok {
		r1 = rf(channelID, name, embed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateway_CreateForumPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForumPost'
type MockGateway_CreateForumPost_Call struct {
	*mock.Call
}

// CreateForumPost is a helper method to define mock.On call
//   - channelID string
//   - name string
//   - embed *discordgo.MessageEmbed
func (_e *MockGateway_Expecter) CreateForumPost(channelID interface{}, name interface{}, embed interface{}) *MockGateway_CreateForumPost_Call {
	return &MockGateway_CreateForumPost_Call{Call: _e.mock.On("CreateForumPost", channelID, name, embed)}
}

func (_c *MockGateway_CreateForumPost_Call) Run(run func(channelID string, name string, embed *discordgo.MessageEmbed)) *MockGateway_CreateForumPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*discordgo.MessageEmbed))
	})
	return _c
}

func (_c *MockGateway_CreateForumPost_Call) Return(threadID string, err error) *MockGateway_CreateForumPost_Call {
	_c.Call.Return(threadID, err)
	return _c
}

func (_c *MockGateway_CreateForumPost_Call) RunAndReturn(run func(string, string, *discordgo.MessageEmbed) (string, error)) *MockGateway_CreateForumPost_Call {
	_c.Call.Return(run)
	return _c
}

// EditOriginalResponse provides a mock function with given fields: appID, token, content
func (_m *MockGateway) EditOriginalResponse(appID string, token string, content string) error {
	ret := _m.Called(appID, token, content)

	if len(ret) == 0 {
		panic("no return value specified for EditOriginalResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(appID, token, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_EditOriginalResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOriginalResponse'
type MockGateway_EditOriginalResponse_Call struct {
	*mock.Call
}

// EditOriginalResponse is a helper method to define mock.On call
//   - appID string
//   - token string
//   - content string
func (_e *MockGateway_Expecter) EditOriginalResponse(appID interface{}, token interface{}, content interface{}) *MockGateway_EditOriginalResponse_Call {
	return &MockGateway_EditOriginalResponse_Call{Call: _e.mock.On("EditOriginalResponse", appID, token, content)}
}

func (_c *MockGateway_EditOriginalResponse_Call) Run(run func(appID string, token string, content string)) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGateway_EditOriginalResponse_Call) Return(_a0 error) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_EditOriginalResponse_Call) RunAndReturn(run func(string, string, string) error) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Return(run)
	return _c
}

// EditPost provides a mock function with given fields: threadID, embed
func (_m *MockGateway) EditPost(threadID string, embed *discordgo.MessageEmbed) error {
	ret := _m.Called(threadID, embed)

	if len(ret) == 0 {
		panic("no return value specified for EditPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *discordgo.MessageEmbed) error); ok {
		r0 = rf(threadID, embed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_EditPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditPost'
type MockGateway_EditPost_Call struct {
	*mock.Call
}

// EditPost is a helper method to define mock.On call
//   - threadID string
//   - embed *discordgo.MessageEmbed
func (_e *MockGateway_Expecter) EditPost(threadID interface{}, embed interface{}) *MockGateway_EditPost_Call {
	return &MockGateway_EditPost_Call{Call: _e.mock.On("EditPost", threadID, embed)}
}

func (_c *MockGateway_EditPost_Call) Run(run func(threadID string, embed *discordgo.MessageEmbed)) *MockGateway_EditPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*discordgo.MessageEmbed))
	})
	return _c
}

func (_c *MockGateway_EditPost_Call) Return(_a0 error) *MockGateway_EditPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_EditPost_Call) RunAndReturn(run func(string, *discordgo.MessageEmbed) error) *MockGateway_EditPost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
