// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockReportCSVConfig is an autogenerated mock type for the ReportCSVConfig type
type MockReportCSVConfig struct {
	mock.Mock
}

type MockReportCSVConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportCSVConfig) EXPECT() *MockReportCSVConfig_Expecter {
	return &MockReportCSVConfig_Expecter{mock: &_m.Mock}
}

// ContractsReportCSV provides a mock function with given fields: ctx, serverID
func (_m *MockReportCSVConfig) ContractsReportCSV(ctx context.Context, serverID uuid.UUID) bool {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ContractsReportCSV")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockReportCSVConfig_ContractsReportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractsReportCSV'
type MockReportCSVConfig_ContractsReportCSV_Call struct {
	*mock.Call
}

// ContractsReportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockReportCSVConfig_Expecter) ContractsReportCSV(ctx interface{}, serverID interface{}) *MockReportCSVConfig_ContractsReportCSV_Call {
	return &MockReportCSVConfig_ContractsReportCSV_Call{Call: _e.mock.On("ContractsReportCSV", ctx, serverID)}
}

func (_c *MockReportCSVConfig_ContractsReportCSV_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockReportCSVConfig_ContractsReportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReportCSVConfig_ContractsReportCSV_Call) Return(_a0 bool) *MockReportCSVConfig_ContractsReportCSV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportCSVConfig_ContractsReportCSV_Call) RunAndReturn(run func(context.Context, uuid.UUID) bool) *MockReportCSVConfig_ContractsReportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsReportCSV provides a mock function with given fields: ctx, serverID, enabled
func (_m *MockReportCSVConfig) SetContractsReportCSV(ctx context.Context, serverID uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, serverID, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsReportCSV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, serverID, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportCSVConfig_SetContractsReportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsReportCSV'
type MockReportCSVConfig_SetContractsReportCSV_Call struct {
	*mock.Call
}

// SetContractsReportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - enabled bool
func (_e *MockReportCSVConfig_Expecter) SetContractsReportCSV(ctx interface{}, serverID interface{}, enabled interface{}) *MockReportCSVConfig_SetContractsReportCSV_Call {
	return &MockReportCSVConfig_SetContractsReportCSV_Call{Call: _e.mock.On("SetContractsReportCSV", ctx, serverID, enabled)}
}

func (_c *MockReportCSVConfig_SetContractsReportCSV_Call) Run(run func(ctx context.Context, serverID uuid.UUID, enabled bool)) *MockReportCSVConfig_SetContractsReportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockReportCSVConfig_SetContractsReportCSV_Call) Return(_a0 error) *MockReportCSVConfig_SetContractsReportCSV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportCSVConfig_SetContractsReportCSV_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockReportCSVConfig_SetContractsReportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportCSVConfig creates a new instance of MockReportCSVConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportCSVConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportCSVConfig {
	mock := &MockReportCSVConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
