// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockItemCap is an autogenerated mock type for the ItemCap type
type MockItemCap struct {
	mock.Mock
}

type MockItemCap_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCap) EXPECT() *MockItemCap_Expecter {
	return &MockItemCap_Expecter{mock: &_m.Mock}
}

// ContractsMaxItems provides a mock function with given fields: ctx, serverID
func (_m *MockItemCap) ContractsMaxItems(ctx context.Context, serverID uuid.UUID) (int, bool) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ContractsMaxItems")
	}

	var r0 int
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, bool)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockItemCap_ContractsMaxItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractsMaxItems'
type MockItemCap_ContractsMaxItems_Call struct {
	*mock.Call
}

// ContractsMaxItems is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockItemCap_Expecter) ContractsMaxItems(ctx interface{}, serverID interface{}) *MockItemCap_ContractsMaxItems_Call {
	return &MockItemCap_ContractsMaxItems_Call{Call: _e.mock.On("ContractsMaxItems", ctx, serverID)}
}

func (_c *MockItemCap_ContractsMaxItems_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockItemCap_ContractsMaxItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockItemCap_ContractsMaxItems_Call) Return(_a0 int, _a1 bool) *MockItemCap_ContractsMaxItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemCap_ContractsMaxItems_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, bool)) *MockItemCap_ContractsMaxItems_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsMaxItems provides a mock function with given fields: ctx, serverID, limit
func (_m *MockItemCap) SetContractsMaxItems(ctx context.Context, serverID uuid.UUID, limit int) error {
	ret := _m.Called(ctx, serverID, limit)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsMaxItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, serverID, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemCap_SetContractsMaxItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsMaxItems'
type MockItemCap_SetContractsMaxItems_Call struct {
	*mock.Call
}

// SetContractsMaxItems is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - limit int
func (_e *MockItemCap_Expecter) SetContractsMaxItems(ctx interface{}, serverID interface{}, limit interface{}) *MockItemCap_SetContractsMaxItems_Call {
	return &MockItemCap_SetContractsMaxItems_Call{Call: _e.mock.On("SetContractsMaxItems", ctx, serverID, limit)}
}

func (_c *MockItemCap_SetContractsMaxItems_Call) Run(run func(ctx context.Context, serverID uuid.UUID, limit int)) *MockItemCap_SetContractsMaxItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockItemCap_SetContractsMaxItems_Call) Return(_a0 error) *MockItemCap_SetContractsMaxItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemCap_SetContractsMaxItems_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *MockItemCap_SetContractsMaxItems_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemCap creates a new instance of MockItemCap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCap(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCap {
	mock := &MockItemCap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
