// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	discordgo "github.com/bwmarrin/discordgo"
	mock "github.com/stretchr/testify/mock"
)

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// ClosePost provides a mock function with given fields: threadID, components
func (_m *MockGateway) ClosePost(threadID string, components []discordgo.MessageComponent) error {
	ret := _m.Called(threadID, components)

	if len(ret) == 0 {
		panic("no return value specified for ClosePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []discordgo.MessageComponent) error); ok {
		r0 = rf(threadID, components)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_ClosePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePost'
type MockGateway_ClosePost_Call struct {
	*mock.Call
}

// ClosePost is a helper method to define mock.On call
//   - threadID string
//   - components []discordgo.MessageComponent
func (_e *MockGateway_Expecter) ClosePost(threadID interface{}, components interface{}) *MockGateway_ClosePost_Call {
	return &MockGateway_ClosePost_Call{Call: _e.mock.On("ClosePost", threadID, components)}
}

func (_c *MockGateway_ClosePost_Call) Run(run func(threadID string, components []discordgo.MessageComponent)) *MockGateway_ClosePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]discordgo.MessageComponent))
	})
	return _c
}

func (_c *MockGateway_ClosePost_Call) Return(_a0 error) *MockGateway_ClosePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_ClosePost_Call) RunAndReturn(run func(string, []discordgo.MessageComponent) error) *MockGateway_ClosePost_Call {
	_c.Call.Return(run)
	return _c
}

// CommentPost provides a mock function with given fields: threadID, content, mentionUserIDs
func (_m *MockGateway) CommentPost(threadID string, content string, mentionUserIDs []string) error {
	ret := _m.Called(threadID, content, mentionUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for CommentPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(threadID, content, mentionUserIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_CommentPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommentPost'
type MockGateway_CommentPost_Call struct {
	*mock.Call
}

// CommentPost is a helper method to define mock.On call
//   - threadID string
//   - content string
//   - mentionUserIDs []string
func (_e *MockGateway_Expecter) CommentPost(threadID interface{}, content interface{}, mentionUserIDs interface{}) *MockGateway_CommentPost_Call {
	return &MockGateway_CommentPost_Call{Call: _e.mock.On("CommentPost", threadID, content, mentionUserIDs)}
}

func (_c *MockGateway_CommentPost_Call) Run(run func(threadID string, content string, mentionUserIDs []string)) *MockGateway_CommentPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockGateway_CommentPost_Call) Return(_a0 error) *MockGateway_CommentPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_CommentPost_Call) RunAndReturn(run func(string, string, []string) error) *MockGateway_CommentPost_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForumPost provides a mock function with given fields: channelID, name, components
func (_m *MockGateway) CreateForumPost(channelID string, name string, components []discordgo.MessageComponent) (string, error) {
	ret := _m.Called(channelID, name, components)

	if len(ret) == 0 {
		panic("no return value specified for CreateForumPost")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []discordgo.MessageComponent) (string, error)); ok {
		return rf(channelID, name, components)
	}
	if rf, ok := ret.Get(0).(func(string, string, []discordgo.MessageComponent) string); ok {
		r0 = rf(channelID, name, components)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, []discordgo.MessageComponent) error); ok {
		r1 = rf(channelID, name, components)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateway_CreateForumPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForumPost'
type MockGateway_CreateForumPost_Call struct {
	*mock.Call
}

// CreateForumPost is a helper method to define mock.On call
//   - channelID string
//   - name string
//   - components []discordgo.MessageComponent
func (_e *MockGateway_Expecter) CreateForumPost(channelID interface{}, name interface{}, components interface{}) *MockGateway_CreateForumPost_Call {
	return &MockGateway_CreateForumPost_Call{Call: _e.mock.On("CreateForumPost", channelID, name, components)}
}

func (_c *MockGateway_CreateForumPost_Call) Run(run func(channelID string, name string, components []discordgo.MessageComponent)) *MockGateway_CreateForumPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]discordgo.MessageComponent))
	})
	return _c
}

func (_c *MockGateway_CreateForumPost_Call) Return(threadID string, err error) *MockGateway_CreateForumPost_Call {
	_c.Call.Return(threadID, err)
	return _c
}

func (_c *MockGateway_CreateForumPost_Call) RunAndReturn(run func(string, string, []discordgo.MessageComponent) (string, error)) *MockGateway_CreateForumPost_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function with given fields: threadID
func (_m *MockGateway) DeletePost(threadID string) error {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockGateway_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - threadID string
func (_e *MockGateway_Expecter) DeletePost(threadID interface{}) *MockGateway_DeletePost_Call {
	return &MockGateway_DeletePost_Call{Call: _e.mock.On("DeletePost", threadID)}
}

func (_c *MockGateway_DeletePost_Call) Run(run func(threadID string)) *MockGateway_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGateway_DeletePost_Call) Return(_a0 error) *MockGateway_DeletePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_DeletePost_Call) RunAndReturn(run func(string) error) *MockGateway_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// EditOriginalResponse provides a mock function with given fields: appID, token, content
func (_m *MockGateway) EditOriginalResponse(appID string, token string, content string) error {
	ret := _m.Called(appID, token, content)

	if len(ret) == 0 {
		panic("no return value specified for EditOriginalResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(appID, token, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_EditOriginalResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOriginalResponse'
type MockGateway_EditOriginalResponse_Call struct {
	*mock.Call
}

// EditOriginalResponse is a helper method to define mock.On call
//   - appID string
//   - token string
//   - content string
func (_e *MockGateway_Expecter) EditOriginalResponse(appID interface{}, token interface{}, content interface{}) *MockGateway_EditOriginalResponse_Call {
	return &MockGateway_EditOriginalResponse_Call{Call: _e.mock.On("EditOriginalResponse", appID, token, content)}
}

func (_c *MockGateway_EditOriginalResponse_Call) Run(run func(appID string, token string, content string)) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGateway_EditOriginalResponse_Call) Return(_a0 error) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_EditOriginalResponse_Call) RunAndReturn(run func(string, string, string) error) *MockGateway_EditOriginalResponse_Call {
	_c.Call.Return(run)
	return _c
}

// EditPost provides a mock function with given fields: threadID, components
func (_m *MockGateway) EditPost(threadID string, components []discordgo.MessageComponent) error {
	ret := _m.Called(threadID, components)

	if len(ret) == 0 {
		panic("no return value specified for EditPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []discordgo.MessageComponent) error); ok {
		r0 = rf(threadID, components)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGateway_EditPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditPost'
type MockGateway_EditPost_Call struct {
	*mock.Call
}

// EditPost is a helper method to define mock.On call
//   - threadID string
//   - components []discordgo.MessageComponent
func (_e *MockGateway_Expecter) EditPost(threadID interface{}, components interface{}) *MockGateway_EditPost_Call {
	return &MockGateway_EditPost_Call{Call: _e.mock.On("EditPost", threadID, components)}
}

func (_c *MockGateway_EditPost_Call) Run(run func(threadID string, components []discordgo.MessageComponent)) *MockGateway_EditPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]discordgo.MessageComponent))
	})
	return _c
}

func (_c *MockGateway_EditPost_Call) Return(_a0 error) *MockGateway_EditPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGateway_EditPost_Call) RunAndReturn(run func(string, []discordgo.MessageComponent) error) *MockGateway_EditPost_Call {
	_c.Call.Return(run)
	return _c
}

// PostIsComponentsV2 provides a mock function with given fields: threadID
func (_m *MockGateway) PostIsComponentsV2(threadID string) (bool, error) {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for PostIsComponentsV2")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(threadID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(threadID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGateway_PostIsComponentsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostIsComponentsV2'
type MockGateway_PostIsComponentsV2_Call struct {
	*mock.Call
}

// PostIsComponentsV2 is a helper method to define mock.On call
//   - threadID string
func (_e *MockGateway_Expecter) PostIsComponentsV2(threadID interface{}) *MockGateway_PostIsComponentsV2_Call {
	return &MockGateway_PostIsComponentsV2_Call{Call: _e.mock.On("PostIsComponentsV2", threadID)}
}

func (_c *MockGateway_PostIsComponentsV2_Call) Run(run func(threadID string)) *MockGateway_PostIsComponentsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGateway_PostIsComponentsV2_Call) Return(_a0 bool, _a1 error) *MockGateway_PostIsComponentsV2_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGateway_PostIsComponentsV2_Call) RunAndReturn(run func(string) (bool, error)) *MockGateway_PostIsComponentsV2_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
