// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	uuid "github.com/google/uuid"
	contracts "github.com/kweezl/spacecraft-corporation/internal/features/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, serverID, threadID, itemName, qty, maxItems, actor
func (_m *MockRepository) AddItem(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, qty int, maxItems int, actor string) error {
	ret := _m.Called(ctx, serverID, threadID, itemName, qty, maxItems, actor)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int, int, string) error); ok {
		r0 = rf(ctx, serverID, threadID, itemName, qty, maxItems, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - qty int
//   - maxItems int
//   - actor string
func (_e *MockRepository_Expecter) AddItem(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, qty interface{}, maxItems interface{}, actor interface{}) *MockRepository_AddItem_Call {
	return &MockRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, serverID, threadID, itemName, qty, maxItems, actor)}
}

func (_c *MockRepository_AddItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, qty int, maxItems int, actor string)) *MockRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_AddItem_Call) Return(_a0 error) *MockRepository_AddItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int, int, string) error) *MockRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function with given fields: ctx, serverID, threadID, actor
func (_m *MockRepository) Cancel(ctx context.Context, serverID uuid.UUID, threadID string, actor string) error {
	ret := _m.Called(ctx, serverID, threadID, actor)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, serverID, threadID, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - actor string
func (_e *MockRepository_Expecter) Cancel(ctx interface{}, serverID interface{}, threadID interface{}, actor interface{}) *MockRepository_Cancel_Call {
	return &MockRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, serverID, threadID, actor)}
}

func (_c *MockRepository_Cancel_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, actor string)) *MockRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_Cancel_Call) Return(_a0 error) *MockRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Cancel_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *MockRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockRepository) Create(ctx context.Context, in contracts.CreateInput) (uuid.UUID, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.CreateInput) (uuid.UUID, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.CreateInput) uuid.UUID); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in contracts.CreateInput
func (_e *MockRepository_Expecter) Create(ctx interface{}, in interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, in contracts.CreateInput)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.CreateInput))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, contracts.CreateInput) (uuid.UUID, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deliver provides a mock function with given fields: ctx, serverID, threadID, itemName, userID, qty
func (_m *MockRepository) Deliver(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int) (bool, error) {
	ret := _m.Called(ctx, serverID, threadID, itemName, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Deliver")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (bool, error)); ok {
		return rf(ctx, serverID, threadID, itemName, userID, qty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) bool); ok {
		r0 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Deliver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deliver'
type MockRepository_Deliver_Call struct {
	*mock.Call
}

// Deliver is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Deliver(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, userID interface{}, qty interface{}) *MockRepository_Deliver_Call {
	return &MockRepository_Deliver_Call{Call: _e.mock.On("Deliver", ctx, serverID, threadID, itemName, userID, qty)}
}

func (_c *MockRepository_Deliver_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int)) *MockRepository_Deliver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Deliver_Call) Return(complete bool, err error) *MockRepository_Deliver_Call {
	_c.Call.Return(complete, err)
	return _c
}

func (_c *MockRepository_Deliver_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) (bool, error)) *MockRepository_Deliver_Call {
	_c.Call.Return(run)
	return _c
}

// DueContracts provides a mock function with given fields: ctx, now, limit
func (_m *MockRepository) DueContracts(ctx context.Context, now time.Time, limit int) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for DueContracts")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]uuid.UUID, error)); ok {
		return rf(ctx, now, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []uuid.UUID); ok {
		r0 = rf(ctx, now, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DueContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DueContracts'
type MockRepository_DueContracts_Call struct {
	*mock.Call
}

// DueContracts is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int
func (_e *MockRepository_Expecter) DueContracts(ctx interface{}, now interface{}, limit interface{}) *MockRepository_DueContracts_Call {
	return &MockRepository_DueContracts_Call{Call: _e.mock.On("DueContracts", ctx, now, limit)}
}

func (_c *MockRepository_DueContracts_Call) Run(run func(ctx context.Context, now time.Time, limit int)) *MockRepository_DueContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_DueContracts_Call) Return(_a0 []uuid.UUID, _a1 error) *MockRepository_DueContracts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DueContracts_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]uuid.UUID, error)) *MockRepository_DueContracts_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, serverID, status, limit, offset
func (_m *MockRepository) List(ctx context.Context, serverID uuid.UUID, status string, limit int, offset int) ([]contracts.ListEntry, int, error) {
	ret := _m.Called(ctx, serverID, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []contracts.ListEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) ([]contracts.ListEntry, int, error)); ok {
		return rf(ctx, serverID, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) []contracts.ListEntry); ok {
		r0 = rf(ctx, serverID, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.ListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) int); ok {
		r1 = rf(ctx, serverID, status, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r2 = rf(ctx, serverID, status, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - status string
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) List(ctx interface{}, serverID interface{}, status interface{}, limit interface{}, offset interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, serverID, status, limit, offset)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, serverID uuid.UUID, status string, limit int, offset int)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(page []contracts.ListEntry, total int, err error) *MockRepository_List_Call {
	_c.Call.Return(page, total, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, int, int) ([]contracts.ListEntry, int, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkExpired provides a mock function with given fields: ctx, id, now
func (_m *MockRepository) MarkExpired(ctx context.Context, id uuid.UUID, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkExpired")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MarkExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkExpired'
type MockRepository_MarkExpired_Call struct {
	*mock.Call
}

// MarkExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkExpired(ctx interface{}, id interface{}, now interface{}) *MockRepository_MarkExpired_Call {
	return &MockRepository_MarkExpired_Call{Call: _e.mock.On("MarkExpired", ctx, id, now)}
}

func (_c *MockRepository_MarkExpired_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *MockRepository_MarkExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_MarkExpired_Call) Return(_a0 bool, _a1 error) *MockRepository_MarkExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MarkExpired_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRepository_MarkExpired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNotified provides a mock function with given fields: ctx, id, now
func (_m *MockRepository) MarkNotified(ctx context.Context, id uuid.UUID, now time.Time) (bool, error) {
	ret := _m.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkNotified")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (bool, error)); ok {
		return rf(ctx, id, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) bool); ok {
		r0 = rf(ctx, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, id, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MarkNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNotified'
type MockRepository_MarkNotified_Call struct {
	*mock.Call
}

// MarkNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkNotified(ctx interface{}, id interface{}, now interface{}) *MockRepository_MarkNotified_Call {
	return &MockRepository_MarkNotified_Call{Call: _e.mock.On("MarkNotified", ctx, id, now)}
}

func (_c *MockRepository_MarkNotified_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *MockRepository_MarkNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_MarkNotified_Call) Return(_a0 bool, _a1 error) *MockRepository_MarkNotified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MarkNotified_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (bool, error)) *MockRepository_MarkNotified_Call {
	_c.Call.Return(run)
	return _c
}

// MemberOutstanding provides a mock function with given fields: ctx, serverID, threadID, userID
func (_m *MockRepository) MemberOutstanding(ctx context.Context, serverID uuid.UUID, threadID string, userID string) ([]contracts.MemberItem, error) {
	ret := _m.Called(ctx, serverID, threadID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MemberOutstanding")
	}

	var r0 []contracts.MemberItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]contracts.MemberItem, error)); ok {
		return rf(ctx, serverID, threadID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []contracts.MemberItem); ok {
		r0 = rf(ctx, serverID, threadID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.MemberItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, serverID, threadID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MemberOutstanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberOutstanding'
type MockRepository_MemberOutstanding_Call struct {
	*mock.Call
}

// MemberOutstanding is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - userID string
func (_e *MockRepository_Expecter) MemberOutstanding(ctx interface{}, serverID interface{}, threadID interface{}, userID interface{}) *MockRepository_MemberOutstanding_Call {
	return &MockRepository_MemberOutstanding_Call{Call: _e.mock.On("MemberOutstanding", ctx, serverID, threadID, userID)}
}

func (_c *MockRepository_MemberOutstanding_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, userID string)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) Return(_a0 []contracts.MemberItem, _a1 error) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]contracts.MemberItem, error)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyDue provides a mock function with given fields: ctx, now, within, limit
func (_m *MockRepository) NotifyDue(ctx context.Context, now time.Time, within time.Duration, limit int) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, now, within, limit)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDue")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) ([]uuid.UUID, error)); ok {
		return rf(ctx, now, within, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) []uuid.UUID); ok {
		r0 = rf(ctx, now, within, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Duration, int) error); ok {
		r1 = rf(ctx, now, within, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_NotifyDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDue'
type MockRepository_NotifyDue_Call struct {
	*mock.Call
}

// NotifyDue is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - within time.Duration
//   - limit int
func (_e *MockRepository_Expecter) NotifyDue(ctx interface{}, now interface{}, within interface{}, limit interface{}) *MockRepository_NotifyDue_Call {
	return &MockRepository_NotifyDue_Call{Call: _e.mock.On("NotifyDue", ctx, now, within, limit)}
}

func (_c *MockRepository_NotifyDue_Call) Run(run func(ctx context.Context, now time.Time, within time.Duration, limit int)) *MockRepository_NotifyDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Duration), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_NotifyDue_Call) Return(_a0 []uuid.UUID, _a1 error) *MockRepository_NotifyDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_NotifyDue_Call) RunAndReturn(run func(context.Context, time.Time, time.Duration, int) ([]uuid.UUID, error)) *MockRepository_NotifyDue_Call {
	_c.Call.Return(run)
	return _c
}

// OutstandingParticipantUserIDs provides a mock function with given fields: ctx, contractID
func (_m *MockRepository) OutstandingParticipantUserIDs(ctx context.Context, contractID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for OutstandingParticipantUserIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, contractID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_OutstandingParticipantUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutstandingParticipantUserIDs'
type MockRepository_OutstandingParticipantUserIDs_Call struct {
	*mock.Call
}

// OutstandingParticipantUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) OutstandingParticipantUserIDs(ctx interface{}, contractID interface{}) *MockRepository_OutstandingParticipantUserIDs_Call {
	return &MockRepository_OutstandingParticipantUserIDs_Call{Call: _e.mock.On("OutstandingParticipantUserIDs", ctx, contractID)}
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) Run(run func(ctx context.Context, contractID uuid.UUID)) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) Return(_a0 []string, _a1 error) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_OutstandingParticipantUserIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockRepository_OutstandingParticipantUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Participate provides a mock function with given fields: ctx, serverID, threadID, itemName, userID, qty
func (_m *MockRepository) Participate(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int) error {
	ret := _m.Called(ctx, serverID, threadID, itemName, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Participate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r0 = rf(ctx, serverID, threadID, itemName, userID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Participate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Participate'
type MockRepository_Participate_Call struct {
	*mock.Call
}

// Participate is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Participate(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, userID interface{}, qty interface{}) *MockRepository_Participate_Call {
	return &MockRepository_Participate_Call{Call: _e.mock.On("Participate", ctx, serverID, threadID, itemName, userID, qty)}
}

func (_c *MockRepository_Participate_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, userID string, qty int)) *MockRepository_Participate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Participate_Call) Return(_a0 error) *MockRepository_Participate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Participate_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) error) *MockRepository_Participate_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with given fields: ctx, serverID, threadID
func (_m *MockRepository) Progress(ctx context.Context, serverID uuid.UUID, threadID string) (contracts.Progress, error) {
	ret := _m.Called(ctx, serverID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (contracts.Progress, error)); ok {
		return rf(ctx, serverID, threadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) contracts.Progress); ok {
		r0 = rf(ctx, serverID, threadID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, serverID, threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockRepository_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) Progress(ctx interface{}, serverID interface{}, threadID interface{}) *MockRepository_Progress_Call {
	return &MockRepository_Progress_Call{Call: _e.mock.On("Progress", ctx, serverID, threadID)}
}

func (_c *MockRepository_Progress_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string)) *MockRepository_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Progress_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_Progress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Progress_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (contracts.Progress, error)) *MockRepository_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByID provides a mock function with given fields: ctx, contractID
func (_m *MockRepository) ProgressByID(ctx context.Context, contractID uuid.UUID) (contracts.Progress, error) {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByID")
	}

	var r0 contracts.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contracts.Progress, error)); ok {
		return rf(ctx, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) contracts.Progress); ok {
		r0 = rf(ctx, contractID)
	} else {
		r0 = ret.Get(0).(contracts.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByID'
type MockRepository_ProgressByID_Call struct {
	*mock.Call
}

// ProgressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByID(ctx interface{}, contractID interface{}) *MockRepository_ProgressByID_Call {
	return &MockRepository_ProgressByID_Call{Call: _e.mock.On("ProgressByID", ctx, contractID)}
}

func (_c *MockRepository_ProgressByID_Call) Run(run func(ctx context.Context, contractID uuid.UUID)) *MockRepository_ProgressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByID_Call) Return(_a0 contracts.Progress, _a1 error) *MockRepository_ProgressByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (contracts.Progress, error)) *MockRepository_ProgressByID_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, serverID, threadID, itemName, targetUserID, qty, actor
func (_m *MockRepository) Release(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, targetUserID string, qty int, actor string) error {
	ret := _m.Called(ctx, serverID, threadID, itemName, targetUserID, qty, actor)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int, string) error); ok {
		r0 = rf(ctx, serverID, threadID, itemName, targetUserID, qty, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - targetUserID string
//   - qty int
//   - actor string
func (_e *MockRepository_Expecter) Release(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, targetUserID interface{}, qty interface{}, actor interface{}) *MockRepository_Release_Call {
	return &MockRepository_Release_Call{Call: _e.mock.On("Release", ctx, serverID, threadID, itemName, targetUserID, qty, actor)}
}

func (_c *MockRepository_Release_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, targetUserID string, qty int, actor string)) *MockRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_Release_Call) Return(_a0 error) *MockRepository_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Release_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int, string) error) *MockRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function with given fields: ctx, serverID, threadID, itemName, actor
func (_m *MockRepository) RemoveItem(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, actor string) (int, error) {
	ret := _m.Called(ctx, serverID, threadID, itemName, actor)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (int, error)); ok {
		return rf(ctx, serverID, threadID, itemName, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) int); ok {
		r0 = rf(ctx, serverID, threadID, itemName, actor)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, serverID, threadID, itemName, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - itemName string
//   - actor string
func (_e *MockRepository_Expecter) RemoveItem(ctx interface{}, serverID interface{}, threadID interface{}, itemName interface{}, actor interface{}) *MockRepository_RemoveItem_Call {
	return &MockRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, serverID, threadID, itemName, actor)}
}

func (_c *MockRepository_RemoveItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, itemName string, actor string)) *MockRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockRepository_RemoveItem_Call) Return(cleared int, err error) *MockRepository_RemoveItem_Call {
	_c.Call.Return(cleared, err)
	return _c
}

func (_c *MockRepository_RemoveItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string) (int, error)) *MockRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// SetThreadID provides a mock function with given fields: ctx, contractID, threadID
func (_m *MockRepository) SetThreadID(ctx context.Context, contractID uuid.UUID, threadID string) error {
	ret := _m.Called(ctx, contractID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for SetThreadID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, contractID, threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThreadID'
type MockRepository_SetThreadID_Call struct {
	*mock.Call
}

// SetThreadID is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) SetThreadID(ctx interface{}, contractID interface{}, threadID interface{}) *MockRepository_SetThreadID_Call {
	return &MockRepository_SetThreadID_Call{Call: _e.mock.On("SetThreadID", ctx, contractID, threadID)}
}

func (_c *MockRepository_SetThreadID_Call) Run(run func(ctx context.Context, contractID uuid.UUID, threadID string)) *MockRepository_SetThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetThreadID_Call) Return(_a0 error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetThreadID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
