// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MockRewardDefaults is an autogenerated mock type for the RewardDefaults type
type MockRewardDefaults struct {
	mock.Mock
}

type MockRewardDefaults_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRewardDefaults) EXPECT() *MockRewardDefaults_Expecter {
	return &MockRewardDefaults_Expecter{mock: &_m.Mock}
}

// ContractsRewardFactor provides a mock function with given fields: ctx, serverID
func (_m *MockRewardDefaults) ContractsRewardFactor(ctx context.Context, serverID uuid.UUID) decimal.Decimal {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ContractsRewardFactor")
	}

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) decimal.Decimal); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	return r0
}

// MockRewardDefaults_ContractsRewardFactor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContractsRewardFactor'
type MockRewardDefaults_ContractsRewardFactor_Call struct {
	*mock.Call
}

// ContractsRewardFactor is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockRewardDefaults_Expecter) ContractsRewardFactor(ctx interface{}, serverID interface{}) *MockRewardDefaults_ContractsRewardFactor_Call {
	return &MockRewardDefaults_ContractsRewardFactor_Call{Call: _e.mock.On("ContractsRewardFactor", ctx, serverID)}
}

func (_c *MockRewardDefaults_ContractsRewardFactor_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockRewardDefaults_ContractsRewardFactor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRewardDefaults_ContractsRewardFactor_Call) Return(_a0 decimal.Decimal) *MockRewardDefaults_ContractsRewardFactor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRewardDefaults_ContractsRewardFactor_Call) RunAndReturn(run func(context.Context, uuid.UUID) decimal.Decimal) *MockRewardDefaults_ContractsRewardFactor_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsRewardFactor provides a mock function with given fields: ctx, serverID, factor
func (_m *MockRewardDefaults) SetContractsRewardFactor(ctx context.Context, serverID uuid.UUID, factor decimal.Decimal) error {
	ret := _m.Called(ctx, serverID, factor)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsRewardFactor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, serverID, factor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRewardDefaults_SetContractsRewardFactor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsRewardFactor'
type MockRewardDefaults_SetContractsRewardFactor_Call struct {
	*mock.Call
}

// SetContractsRewardFactor is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - factor decimal.Decimal
func (_e *MockRewardDefaults_Expecter) SetContractsRewardFactor(ctx interface{}, serverID interface{}, factor interface{}) *MockRewardDefaults_SetContractsRewardFactor_Call {
	return &MockRewardDefaults_SetContractsRewardFactor_Call{Call: _e.mock.On("SetContractsRewardFactor", ctx, serverID, factor)}
}

func (_c *MockRewardDefaults_SetContractsRewardFactor_Call) Run(run func(ctx context.Context, serverID uuid.UUID, factor decimal.Decimal)) *MockRewardDefaults_SetContractsRewardFactor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRewardDefaults_SetContractsRewardFactor_Call) Return(_a0 error) *MockRewardDefaults_SetContractsRewardFactor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRewardDefaults_SetContractsRewardFactor_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRewardDefaults_SetContractsRewardFactor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRewardDefaults creates a new instance of MockRewardDefaults. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRewardDefaults(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRewardDefaults {
	mock := &MockRewardDefaults{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
