// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	contracts "github.com/kweezl/spacecraft-corporation/internal/features/contracts"
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// AddTemplateItem provides a mock function with given fields: ctx, serverID, templateID, gdid, gdVersion, qty, maxItems, actor
func (_m *MockTemplateRepository) AddTemplateItem(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, gdid string, gdVersion string, qty int, maxItems int, actor string) error {
	ret := _m.Called(ctx, serverID, templateID, gdid, gdVersion, qty, maxItems, actor)

	if len(ret) == 0 {
		panic("no return value specified for AddTemplateItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, int, string) error); ok {
		r0 = rf(ctx, serverID, templateID, gdid, gdVersion, qty, maxItems, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_AddTemplateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTemplateItem'
type MockTemplateRepository_AddTemplateItem_Call struct {
	*mock.Call
}

// AddTemplateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
//   - gdid string
//   - gdVersion string
//   - qty int
//   - maxItems int
//   - actor string
func (_e *MockTemplateRepository_Expecter) AddTemplateItem(ctx interface{}, serverID interface{}, templateID interface{}, gdid interface{}, gdVersion interface{}, qty interface{}, maxItems interface{}, actor interface{}) *MockTemplateRepository_AddTemplateItem_Call {
	return &MockTemplateRepository_AddTemplateItem_Call{Call: _e.mock.On("AddTemplateItem", ctx, serverID, templateID, gdid, gdVersion, qty, maxItems, actor)}
}

func (_c *MockTemplateRepository_AddTemplateItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, gdid string, gdVersion string, qty int, maxItems int, actor string)) *MockTemplateRepository_AddTemplateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(int), args[6].(int), args[7].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_AddTemplateItem_Call) Return(_a0 error) *MockTemplateRepository_AddTemplateItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_AddTemplateItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, int, int, string) error) *MockTemplateRepository_AddTemplateItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function with given fields: ctx, serverID, title, description, actor
func (_m *MockTemplateRepository) CreateTemplate(ctx context.Context, serverID uuid.UUID, title string, description string, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, title, description, actor)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, title, description, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, title, description, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, serverID, title, description, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockTemplateRepository_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - title string
//   - description string
//   - actor string
func (_e *MockTemplateRepository_Expecter) CreateTemplate(ctx interface{}, serverID interface{}, title interface{}, description interface{}, actor interface{}) *MockTemplateRepository_CreateTemplate_Call {
	return &MockTemplateRepository_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, serverID, title, description, actor)}
}

func (_c *MockTemplateRepository_CreateTemplate_Call) Run(run func(ctx context.Context, serverID uuid.UUID, title string, description string, actor string)) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_CreateTemplate_Call) Return(_a0 uuid.UUID, _a1 error) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_CreateTemplate_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string) (uuid.UUID, error)) *MockTemplateRepository_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function with given fields: ctx, serverID, templateID, actor
func (_m *MockTemplateRepository) DeleteTemplate(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, actor string) error {
	ret := _m.Called(ctx, serverID, templateID, actor)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, templateID, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockTemplateRepository_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
//   - actor string
func (_e *MockTemplateRepository_Expecter) DeleteTemplate(ctx interface{}, serverID interface{}, templateID interface{}, actor interface{}) *MockTemplateRepository_DeleteTemplate_Call {
	return &MockTemplateRepository_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, serverID, templateID, actor)}
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, actor string)) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) Return(_a0 error) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_DeleteTemplate_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockTemplateRepository_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function with given fields: ctx, serverID, titleQuery, limit, offset
func (_m *MockTemplateRepository) ListTemplates(ctx context.Context, serverID uuid.UUID, titleQuery string, limit int, offset int) ([]contracts.TemplateListEntry, int, error) {
	ret := _m.Called(ctx, serverID, titleQuery, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []contracts.TemplateListEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) ([]contracts.TemplateListEntry, int, error)); ok {
		return rf(ctx, serverID, titleQuery, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) []contracts.TemplateListEntry); ok {
		r0 = rf(ctx, serverID, titleQuery, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.TemplateListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) int); ok {
		r1 = rf(ctx, serverID, titleQuery, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r2 = rf(ctx, serverID, titleQuery, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTemplateRepository_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type MockTemplateRepository_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - titleQuery string
//   - limit int
//   - offset int
func (_e *MockTemplateRepository_Expecter) ListTemplates(ctx interface{}, serverID interface{}, titleQuery interface{}, limit interface{}, offset interface{}) *MockTemplateRepository_ListTemplates_Call {
	return &MockTemplateRepository_ListTemplates_Call{Call: _e.mock.On("ListTemplates", ctx, serverID, titleQuery, limit, offset)}
}

func (_c *MockTemplateRepository_ListTemplates_Call) Run(run func(ctx context.Context, serverID uuid.UUID, titleQuery string, limit int, offset int)) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockTemplateRepository_ListTemplates_Call) Return(page []contracts.TemplateListEntry, total int, err error) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Return(page, total, err)
	return _c
}

func (_c *MockTemplateRepository_ListTemplates_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, int, int) ([]contracts.TemplateListEntry, int, error)) *MockTemplateRepository_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTemplateItem provides a mock function with given fields: ctx, serverID, templateItemID, actor
func (_m *MockTemplateRepository) RemoveTemplateItem(ctx context.Context, serverID uuid.UUID, templateItemID uuid.UUID, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, templateItemID, actor)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTemplateItem")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, templateItemID, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, templateItemID, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, serverID, templateItemID, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_RemoveTemplateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTemplateItem'
type MockTemplateRepository_RemoveTemplateItem_Call struct {
	*mock.Call
}

// RemoveTemplateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateItemID uuid.UUID
//   - actor string
func (_e *MockTemplateRepository_Expecter) RemoveTemplateItem(ctx interface{}, serverID interface{}, templateItemID interface{}, actor interface{}) *MockTemplateRepository_RemoveTemplateItem_Call {
	return &MockTemplateRepository_RemoveTemplateItem_Call{Call: _e.mock.On("RemoveTemplateItem", ctx, serverID, templateItemID, actor)}
}

func (_c *MockTemplateRepository_RemoveTemplateItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateItemID uuid.UUID, actor string)) *MockTemplateRepository_RemoveTemplateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_RemoveTemplateItem_Call) Return(templateID uuid.UUID, err error) *MockTemplateRepository_RemoveTemplateItem_Call {
	_c.Call.Return(templateID, err)
	return _c
}

func (_c *MockTemplateRepository_RemoveTemplateItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)) *MockTemplateRepository_RemoveTemplateItem_Call {
	_c.Call.Return(run)
	return _c
}

// SetTemplateLocation provides a mock function with given fields: ctx, serverID, templateID, gdid, gdVersion, actor
func (_m *MockTemplateRepository) SetTemplateLocation(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, gdid string, gdVersion string, actor string) error {
	ret := _m.Called(ctx, serverID, templateID, gdid, gdVersion, actor)

	if len(ret) == 0 {
		panic("no return value specified for SetTemplateLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, serverID, templateID, gdid, gdVersion, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_SetTemplateLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTemplateLocation'
type MockTemplateRepository_SetTemplateLocation_Call struct {
	*mock.Call
}

// SetTemplateLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
//   - gdid string
//   - gdVersion string
//   - actor string
func (_e *MockTemplateRepository_Expecter) SetTemplateLocation(ctx interface{}, serverID interface{}, templateID interface{}, gdid interface{}, gdVersion interface{}, actor interface{}) *MockTemplateRepository_SetTemplateLocation_Call {
	return &MockTemplateRepository_SetTemplateLocation_Call{Call: _e.mock.On("SetTemplateLocation", ctx, serverID, templateID, gdid, gdVersion, actor)}
}

func (_c *MockTemplateRepository_SetTemplateLocation_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, gdid string, gdVersion string, actor string)) *MockTemplateRepository_SetTemplateLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_SetTemplateLocation_Call) Return(_a0 error) *MockTemplateRepository_SetTemplateLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_SetTemplateLocation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error) *MockTemplateRepository_SetTemplateLocation_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateByID provides a mock function with given fields: ctx, serverID, templateID
func (_m *MockTemplateRepository) TemplateByID(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID) (contracts.Template, error) {
	ret := _m.Called(ctx, serverID, templateID)

	if len(ret) == 0 {
		panic("no return value specified for TemplateByID")
	}

	var r0 contracts.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (contracts.Template, error)); ok {
		return rf(ctx, serverID, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) contracts.Template); ok {
		r0 = rf(ctx, serverID, templateID)
	} else {
		r0 = ret.Get(0).(contracts.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_TemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateByID'
type MockTemplateRepository_TemplateByID_Call struct {
	*mock.Call
}

// TemplateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
func (_e *MockTemplateRepository_Expecter) TemplateByID(ctx interface{}, serverID interface{}, templateID interface{}) *MockTemplateRepository_TemplateByID_Call {
	return &MockTemplateRepository_TemplateByID_Call{Call: _e.mock.On("TemplateByID", ctx, serverID, templateID)}
}

func (_c *MockTemplateRepository_TemplateByID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID)) *MockTemplateRepository_TemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTemplateRepository_TemplateByID_Call) Return(_a0 contracts.Template, _a1 error) *MockTemplateRepository_TemplateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTemplateRepository_TemplateByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (contracts.Template, error)) *MockTemplateRepository_TemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplateDetails provides a mock function with given fields: ctx, serverID, templateID, title, description, deadlineMinutes, actor
func (_m *MockTemplateRepository) UpdateTemplateDetails(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, title string, description string, deadlineMinutes int, actor string) error {
	ret := _m.Called(ctx, serverID, templateID, title, description, deadlineMinutes, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplateDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int, string) error); ok {
		r0 = rf(ctx, serverID, templateID, title, description, deadlineMinutes, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_UpdateTemplateDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplateDetails'
type MockTemplateRepository_UpdateTemplateDetails_Call struct {
	*mock.Call
}

// UpdateTemplateDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
//   - title string
//   - description string
//   - deadlineMinutes int
//   - actor string
func (_e *MockTemplateRepository_Expecter) UpdateTemplateDetails(ctx interface{}, serverID interface{}, templateID interface{}, title interface{}, description interface{}, deadlineMinutes interface{}, actor interface{}) *MockTemplateRepository_UpdateTemplateDetails_Call {
	return &MockTemplateRepository_UpdateTemplateDetails_Call{Call: _e.mock.On("UpdateTemplateDetails", ctx, serverID, templateID, title, description, deadlineMinutes, actor)}
}

func (_c *MockTemplateRepository_UpdateTemplateDetails_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, title string, description string, deadlineMinutes int, actor string)) *MockTemplateRepository_UpdateTemplateDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateDetails_Call) Return(_a0 error) *MockTemplateRepository_UpdateTemplateDetails_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateDetails_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string, int, string) error) *MockTemplateRepository_UpdateTemplateDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplateItemQty provides a mock function with given fields: ctx, serverID, templateItemID, qty, actor
func (_m *MockTemplateRepository) UpdateTemplateItemQty(ctx context.Context, serverID uuid.UUID, templateItemID uuid.UUID, qty int, actor string) (uuid.UUID, error) {
	ret := _m.Called(ctx, serverID, templateItemID, qty, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplateItemQty")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) (uuid.UUID, error)); ok {
		return rf(ctx, serverID, templateItemID, qty, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) uuid.UUID); ok {
		r0 = rf(ctx, serverID, templateItemID, qty, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, string) error); ok {
		r1 = rf(ctx, serverID, templateItemID, qty, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTemplateRepository_UpdateTemplateItemQty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplateItemQty'
type MockTemplateRepository_UpdateTemplateItemQty_Call struct {
	*mock.Call
}

// UpdateTemplateItemQty is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateItemID uuid.UUID
//   - qty int
//   - actor string
func (_e *MockTemplateRepository_Expecter) UpdateTemplateItemQty(ctx interface{}, serverID interface{}, templateItemID interface{}, qty interface{}, actor interface{}) *MockTemplateRepository_UpdateTemplateItemQty_Call {
	return &MockTemplateRepository_UpdateTemplateItemQty_Call{Call: _e.mock.On("UpdateTemplateItemQty", ctx, serverID, templateItemID, qty, actor)}
}

func (_c *MockTemplateRepository_UpdateTemplateItemQty_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateItemID uuid.UUID, qty int, actor string)) *MockTemplateRepository_UpdateTemplateItemQty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateItemQty_Call) Return(templateID uuid.UUID, err error) *MockTemplateRepository_UpdateTemplateItemQty_Call {
	_c.Call.Return(templateID, err)
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateItemQty_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, string) (uuid.UUID, error)) *MockTemplateRepository_UpdateTemplateItemQty_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplateRewards provides a mock function with given fields: ctx, serverID, templateID, credits, reputation, licencePoints, actor
func (_m *MockTemplateRepository) UpdateTemplateRewards(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, credits decimal.Decimal, reputation int, licencePoints int, actor string) error {
	ret := _m.Called(ctx, serverID, templateID, credits, reputation, licencePoints, actor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplateRewards")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal, int, int, string) error); ok {
		r0 = rf(ctx, serverID, templateID, credits, reputation, licencePoints, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplateRepository_UpdateTemplateRewards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplateRewards'
type MockTemplateRepository_UpdateTemplateRewards_Call struct {
	*mock.Call
}

// UpdateTemplateRewards is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - templateID uuid.UUID
//   - credits decimal.Decimal
//   - reputation int
//   - licencePoints int
//   - actor string
func (_e *MockTemplateRepository_Expecter) UpdateTemplateRewards(ctx interface{}, serverID interface{}, templateID interface{}, credits interface{}, reputation interface{}, licencePoints interface{}, actor interface{}) *MockTemplateRepository_UpdateTemplateRewards_Call {
	return &MockTemplateRepository_UpdateTemplateRewards_Call{Call: _e.mock.On("UpdateTemplateRewards", ctx, serverID, templateID, credits, reputation, licencePoints, actor)}
}

func (_c *MockTemplateRepository_UpdateTemplateRewards_Call) Run(run func(ctx context.Context, serverID uuid.UUID, templateID uuid.UUID, credits decimal.Decimal, reputation int, licencePoints int, actor string)) *MockTemplateRepository_UpdateTemplateRewards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(int), args[5].(int), args[6].(string))
	})
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateRewards_Call) Return(_a0 error) *MockTemplateRepository_UpdateTemplateRewards_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplateRepository_UpdateTemplateRewards_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal, int, int, string) error) *MockTemplateRepository_UpdateTemplateRewards_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
