// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	token "github.com/kweezl/spacecraft-cadet/internal/token"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ListEnabled provides a mock function with given fields: ctx
func (_m *MockRepository) ListEnabled(ctx context.Context) ([]token.Token, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEnabled")
	}

	var r0 []token.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]token.Token, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []token.Token); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]token.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnabled'
type MockRepository_ListEnabled_Call struct {
	*mock.Call
}

// ListEnabled is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListEnabled(ctx interface{}) *MockRepository_ListEnabled_Call {
	return &MockRepository_ListEnabled_Call{Call: _e.mock.On("ListEnabled", ctx)}
}

func (_c *MockRepository_ListEnabled_Call) Run(run func(ctx context.Context)) *MockRepository_ListEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_ListEnabled_Call) Return(_a0 []token.Token, _a1 error) *MockRepository_ListEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListEnabled_Call) RunAndReturn(run func(context.Context) ([]token.Token, error)) *MockRepository_ListEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
