// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, serverID
func (_m *MockRepository) Count(ctx context.Context, serverID string) (int64, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockRepository_Expecter) Count(ctx interface{}, serverID interface{}) *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count", ctx, serverID)}
}

func (_c *MockRepository_Count_Call) Run(run func(ctx context.Context, serverID string)) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(_a0 int64, _a1 error) *MockRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: ctx, serverID, userID
func (_m *MockRepository) Record(ctx context.Context, serverID string, userID string) error {
	ret := _m.Called(ctx, serverID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serverID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockRepository_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - userID string
func (_e *MockRepository_Expecter) Record(ctx interface{}, serverID interface{}, userID interface{}) *MockRepository_Record_Call {
	return &MockRepository_Record_Call{Call: _e.mock.On("Record", ctx, serverID, userID)}
}

func (_c *MockRepository_Record_Call) Run(run func(ctx context.Context, serverID string, userID string)) *MockRepository_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Record_Call) Return(_a0 error) *MockRepository_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Record_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
