// Code generated by gamedata/gen. DO NOT EDIT.

package gamedata

import (
	v1 "github.com/kweezl/spacecraft-corporation/internal/gamedata/db/v1"
)

var definedSources = map[string]source{
	"v1": {
		version: v1.Version, parent: v1.Parent,
		items: v1.Items, removedItems: v1.RemovedItems,
		categories: v1.Categories, contracts: v1.Contracts, spaceObjects: v1.SpaceObjects,
		names: v1.Names, descs: v1.Descs, categoryNames: v1.CategoryNames,
	},
}
