// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	i18n "github.com/kweezl/spacecraft-corporation/internal/i18n"
	settings "github.com/kweezl/spacecraft-corporation/internal/settings"
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, serverID
func (_m *MockRepository) Get(ctx context.Context, serverID uuid.UUID) (settings.Settings, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 settings.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (settings.Settings, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) settings.Settings); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(settings.Settings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, serverID interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, serverID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 settings.Settings, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (settings.Settings, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsForumChannelID provides a mock function with given fields: ctx, serverID, channelID
func (_m *MockRepository) SetContractsForumChannelID(ctx context.Context, serverID uuid.UUID, channelID string) error {
	ret := _m.Called(ctx, serverID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsForumChannelID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetContractsForumChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsForumChannelID'
type MockRepository_SetContractsForumChannelID_Call struct {
	*mock.Call
}

// SetContractsForumChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - channelID string
func (_e *MockRepository_Expecter) SetContractsForumChannelID(ctx interface{}, serverID interface{}, channelID interface{}) *MockRepository_SetContractsForumChannelID_Call {
	return &MockRepository_SetContractsForumChannelID_Call{Call: _e.mock.On("SetContractsForumChannelID", ctx, serverID, channelID)}
}

func (_c *MockRepository_SetContractsForumChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, channelID string)) *MockRepository_SetContractsForumChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetContractsForumChannelID_Call) Return(_a0 error) *MockRepository_SetContractsForumChannelID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetContractsForumChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetContractsForumChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsReportsChannelID provides a mock function with given fields: ctx, serverID, channelID
func (_m *MockRepository) SetContractsReportsChannelID(ctx context.Context, serverID uuid.UUID, channelID string) error {
	ret := _m.Called(ctx, serverID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsReportsChannelID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetContractsReportsChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsReportsChannelID'
type MockRepository_SetContractsReportsChannelID_Call struct {
	*mock.Call
}

// SetContractsReportsChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - channelID string
func (_e *MockRepository_Expecter) SetContractsReportsChannelID(ctx interface{}, serverID interface{}, channelID interface{}) *MockRepository_SetContractsReportsChannelID_Call {
	return &MockRepository_SetContractsReportsChannelID_Call{Call: _e.mock.On("SetContractsReportsChannelID", ctx, serverID, channelID)}
}

func (_c *MockRepository_SetContractsReportsChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID, channelID string)) *MockRepository_SetContractsReportsChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetContractsReportsChannelID_Call) Return(_a0 error) *MockRepository_SetContractsReportsChannelID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetContractsReportsChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetContractsReportsChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// SetContractsRewardFactor provides a mock function with given fields: ctx, serverID, factor
func (_m *MockRepository) SetContractsRewardFactor(ctx context.Context, serverID uuid.UUID, factor decimal.Decimal) error {
	ret := _m.Called(ctx, serverID, factor)

	if len(ret) == 0 {
		panic("no return value specified for SetContractsRewardFactor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, serverID, factor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetContractsRewardFactor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContractsRewardFactor'
type MockRepository_SetContractsRewardFactor_Call struct {
	*mock.Call
}

// SetContractsRewardFactor is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - factor decimal.Decimal
func (_e *MockRepository_Expecter) SetContractsRewardFactor(ctx interface{}, serverID interface{}, factor interface{}) *MockRepository_SetContractsRewardFactor_Call {
	return &MockRepository_SetContractsRewardFactor_Call{Call: _e.mock.On("SetContractsRewardFactor", ctx, serverID, factor)}
}

func (_c *MockRepository_SetContractsRewardFactor_Call) Run(run func(ctx context.Context, serverID uuid.UUID, factor decimal.Decimal)) *MockRepository_SetContractsRewardFactor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *MockRepository_SetContractsRewardFactor_Call) Return(_a0 error) *MockRepository_SetContractsRewardFactor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetContractsRewardFactor_Call) RunAndReturn(run func(context.Context, uuid.UUID, decimal.Decimal) error) *MockRepository_SetContractsRewardFactor_Call {
	_c.Call.Return(run)
	return _c
}

// SetLanguage provides a mock function with given fields: ctx, serverID, language
func (_m *MockRepository) SetLanguage(ctx context.Context, serverID uuid.UUID, language i18n.Language) error {
	ret := _m.Called(ctx, serverID, language)

	if len(ret) == 0 {
		panic("no return value specified for SetLanguage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, i18n.Language) error); ok {
		r0 = rf(ctx, serverID, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLanguage'
type MockRepository_SetLanguage_Call struct {
	*mock.Call
}

// SetLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - language i18n.Language
func (_e *MockRepository_Expecter) SetLanguage(ctx interface{}, serverID interface{}, language interface{}) *MockRepository_SetLanguage_Call {
	return &MockRepository_SetLanguage_Call{Call: _e.mock.On("SetLanguage", ctx, serverID, language)}
}

func (_c *MockRepository_SetLanguage_Call) Run(run func(ctx context.Context, serverID uuid.UUID, language i18n.Language)) *MockRepository_SetLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(i18n.Language))
	})
	return _c
}

func (_c *MockRepository_SetLanguage_Call) Return(_a0 error) *MockRepository_SetLanguage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetLanguage_Call) RunAndReturn(run func(context.Context, uuid.UUID, i18n.Language) error) *MockRepository_SetLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// SetTheme provides a mock function with given fields: ctx, serverID, theme
func (_m *MockRepository) SetTheme(ctx context.Context, serverID uuid.UUID, theme string) error {
	ret := _m.Called(ctx, serverID, theme)

	if len(ret) == 0 {
		panic("no return value specified for SetTheme")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, serverID, theme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetTheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTheme'
type MockRepository_SetTheme_Call struct {
	*mock.Call
}

// SetTheme is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - theme string
func (_e *MockRepository_Expecter) SetTheme(ctx interface{}, serverID interface{}, theme interface{}) *MockRepository_SetTheme_Call {
	return &MockRepository_SetTheme_Call{Call: _e.mock.On("SetTheme", ctx, serverID, theme)}
}

func (_c *MockRepository_SetTheme_Call) Run(run func(ctx context.Context, serverID uuid.UUID, theme string)) *MockRepository_SetTheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetTheme_Call) Return(_a0 error) *MockRepository_SetTheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetTheme_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetTheme_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
