// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	settings "github.com/kweezl/spacecraft-corporation/internal/settings"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, serverID
func (_m *MockRepository) Get(ctx context.Context, serverID string) (settings.Settings, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 settings.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (settings.Settings, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) settings.Settings); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(settings.Settings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockRepository_Expecter) Get(ctx interface{}, serverID interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, serverID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, serverID string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 settings.Settings, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, string) (settings.Settings, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SetLanguage provides a mock function with given fields: ctx, serverID, language
func (_m *MockRepository) SetLanguage(ctx context.Context, serverID string, language string) error {
	ret := _m.Called(ctx, serverID, language)

	if len(ret) == 0 {
		panic("no return value specified for SetLanguage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serverID, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLanguage'
type MockRepository_SetLanguage_Call struct {
	*mock.Call
}

// SetLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - language string
func (_e *MockRepository_Expecter) SetLanguage(ctx interface{}, serverID interface{}, language interface{}) *MockRepository_SetLanguage_Call {
	return &MockRepository_SetLanguage_Call{Call: _e.mock.On("SetLanguage", ctx, serverID, language)}
}

func (_c *MockRepository_SetLanguage_Call) Run(run func(ctx context.Context, serverID string, language string)) *MockRepository_SetLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetLanguage_Call) Return(_a0 error) *MockRepository_SetLanguage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetLanguage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_SetLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// SetTheme provides a mock function with given fields: ctx, serverID, theme
func (_m *MockRepository) SetTheme(ctx context.Context, serverID string, theme string) error {
	ret := _m.Called(ctx, serverID, theme)

	if len(ret) == 0 {
		panic("no return value specified for SetTheme")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serverID, theme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetTheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTheme'
type MockRepository_SetTheme_Call struct {
	*mock.Call
}

// SetTheme is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - theme string
func (_e *MockRepository_Expecter) SetTheme(ctx interface{}, serverID interface{}, theme interface{}) *MockRepository_SetTheme_Call {
	return &MockRepository_SetTheme_Call{Call: _e.mock.On("SetTheme", ctx, serverID, theme)}
}

func (_c *MockRepository_SetTheme_Call) Run(run func(ctx context.Context, serverID string, theme string)) *MockRepository_SetTheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetTheme_Call) Return(_a0 error) *MockRepository_SetTheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetTheme_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_SetTheme_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
