// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLimitConfig is an autogenerated mock type for the LimitConfig type
type MockLimitConfig struct {
	mock.Mock
}

type MockLimitConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimitConfig) EXPECT() *MockLimitConfig_Expecter {
	return &MockLimitConfig_Expecter{mock: &_m.Mock}
}

// SupplyRequestLimit provides a mock function with given fields: ctx, serverID
func (_m *MockLimitConfig) SupplyRequestLimit(ctx context.Context, serverID uuid.UUID) (int, bool) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for SupplyRequestLimit")
	}

	var r0 int
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, bool)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockLimitConfig_SupplyRequestLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupplyRequestLimit'
type MockLimitConfig_SupplyRequestLimit_Call struct {
	*mock.Call
}

// SupplyRequestLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockLimitConfig_Expecter) SupplyRequestLimit(ctx interface{}, serverID interface{}) *MockLimitConfig_SupplyRequestLimit_Call {
	return &MockLimitConfig_SupplyRequestLimit_Call{Call: _e.mock.On("SupplyRequestLimit", ctx, serverID)}
}

func (_c *MockLimitConfig_SupplyRequestLimit_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockLimitConfig_SupplyRequestLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLimitConfig_SupplyRequestLimit_Call) Return(_a0 int, _a1 bool) *MockLimitConfig_SupplyRequestLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLimitConfig_SupplyRequestLimit_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, bool)) *MockLimitConfig_SupplyRequestLimit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLimitConfig creates a new instance of MockLimitConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimitConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimitConfig {
	mock := &MockLimitConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
