// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockForumConfig is an autogenerated mock type for the ForumConfig type
type MockForumConfig struct {
	mock.Mock
}

type MockForumConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForumConfig) EXPECT() *MockForumConfig_Expecter {
	return &MockForumConfig_Expecter{mock: &_m.Mock}
}

// SupplyForumChannelID provides a mock function with given fields: ctx, serverID
func (_m *MockForumConfig) SupplyForumChannelID(ctx context.Context, serverID uuid.UUID) (string, bool) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for SupplyForumChannelID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, bool)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockForumConfig_SupplyForumChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupplyForumChannelID'
type MockForumConfig_SupplyForumChannelID_Call struct {
	*mock.Call
}

// SupplyForumChannelID is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
func (_e *MockForumConfig_Expecter) SupplyForumChannelID(ctx interface{}, serverID interface{}) *MockForumConfig_SupplyForumChannelID_Call {
	return &MockForumConfig_SupplyForumChannelID_Call{Call: _e.mock.On("SupplyForumChannelID", ctx, serverID)}
}

func (_c *MockForumConfig_SupplyForumChannelID_Call) Run(run func(ctx context.Context, serverID uuid.UUID)) *MockForumConfig_SupplyForumChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockForumConfig_SupplyForumChannelID_Call) Return(_a0 string, _a1 bool) *MockForumConfig_SupplyForumChannelID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForumConfig_SupplyForumChannelID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, bool)) *MockForumConfig_SupplyForumChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockForumConfig creates a new instance of MockForumConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForumConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForumConfig {
	mock := &MockForumConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
