// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	supply "github.com/kweezl/spacecraft-corporation/internal/features/supply"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, serverID, ownerUserID, requestID, gdid, gdVersion, qty, maxItems
func (_m *MockRepository) AddItem(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, gdid string, gdVersion string, qty int, maxItems int) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID, gdid, gdVersion, qty, maxItems)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, string, string, int, int) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID, gdid, gdVersion, qty, maxItems)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
//   - gdid string
//   - gdVersion string
//   - qty int
//   - maxItems int
func (_e *MockRepository_Expecter) AddItem(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}, gdid interface{}, gdVersion interface{}, qty interface{}, maxItems interface{}) *MockRepository_AddItem_Call {
	return &MockRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, serverID, ownerUserID, requestID, gdid, gdVersion, qty, maxItems)}
}

func (_c *MockRepository_AddItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, gdid string, gdVersion string, qty int, maxItems int)) *MockRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string), args[6].(int), args[7].(int))
	})
	return _c
}

func (_c *MockRepository_AddItem_Call) Return(_a0 error) *MockRepository_AddItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, string, string, int, int) error) *MockRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function with given fields: ctx, serverID, ownerUserID, requestID
func (_m *MockRepository) Cancel(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) Cancel(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}) *MockRepository_Cancel_Call {
	return &MockRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, serverID, ownerUserID, requestID)}
}

func (_c *MockRepository_Cancel_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID)) *MockRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Cancel_Call) Return(_a0 error) *MockRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Cancel_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) error) *MockRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockRepository) Create(ctx context.Context, in supply.CreateInput) (uuid.UUID, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, supply.CreateInput) (uuid.UUID, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, supply.CreateInput) uuid.UUID); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, supply.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in supply.CreateInput
func (_e *MockRepository_Expecter) Create(ctx interface{}, in interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, in supply.CreateInput)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(supply.CreateInput))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, supply.CreateInput) (uuid.UUID, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deliver provides a mock function with given fields: ctx, serverID, threadID, gdid, userID, qty
func (_m *MockRepository) Deliver(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int) (bool, error) {
	ret := _m.Called(ctx, serverID, threadID, gdid, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Deliver")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (bool, error)); ok {
		return rf(ctx, serverID, threadID, gdid, userID, qty)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) bool); ok {
		r0 = rf(ctx, serverID, threadID, gdid, userID, qty)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = rf(ctx, serverID, threadID, gdid, userID, qty)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Deliver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deliver'
type MockRepository_Deliver_Call struct {
	*mock.Call
}

// Deliver is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - gdid string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Deliver(ctx interface{}, serverID interface{}, threadID interface{}, gdid interface{}, userID interface{}, qty interface{}) *MockRepository_Deliver_Call {
	return &MockRepository_Deliver_Call{Call: _e.mock.On("Deliver", ctx, serverID, threadID, gdid, userID, qty)}
}

func (_c *MockRepository_Deliver_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int)) *MockRepository_Deliver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Deliver_Call) Return(complete bool, err error) *MockRepository_Deliver_Call {
	_c.Call.Return(complete, err)
	return _c
}

func (_c *MockRepository_Deliver_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) (bool, error)) *MockRepository_Deliver_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, serverID, ownerUserID, statuses, limit, offset
func (_m *MockRepository) ListByOwner(ctx context.Context, serverID uuid.UUID, ownerUserID string, statuses []supply.Status, limit int, offset int) ([]supply.ListEntry, int, error) {
	ret := _m.Called(ctx, serverID, ownerUserID, statuses, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []supply.ListEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []supply.Status, int, int) ([]supply.ListEntry, int, error)); ok {
		return rf(ctx, serverID, ownerUserID, statuses, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []supply.Status, int, int) []supply.ListEntry); ok {
		r0 = rf(ctx, serverID, ownerUserID, statuses, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]supply.ListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, []supply.Status, int, int) int); ok {
		r1 = rf(ctx, serverID, ownerUserID, statuses, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, []supply.Status, int, int) error); ok {
		r2 = rf(ctx, serverID, ownerUserID, statuses, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockRepository_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - statuses []supply.Status
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListByOwner(ctx interface{}, serverID interface{}, ownerUserID interface{}, statuses interface{}, limit interface{}, offset interface{}) *MockRepository_ListByOwner_Call {
	return &MockRepository_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, serverID, ownerUserID, statuses, limit, offset)}
}

func (_c *MockRepository_ListByOwner_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, statuses []supply.Status, limit int, offset int)) *MockRepository_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].([]supply.Status), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_ListByOwner_Call) Return(_a0 []supply.ListEntry, _a1 int, _a2 error) *MockRepository_ListByOwner_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_ListByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, []supply.Status, int, int) ([]supply.ListEntry, int, error)) *MockRepository_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// MemberOutstanding provides a mock function with given fields: ctx, serverID, threadID, userID
func (_m *MockRepository) MemberOutstanding(ctx context.Context, serverID uuid.UUID, threadID string, userID string) ([]supply.MemberItem, error) {
	ret := _m.Called(ctx, serverID, threadID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MemberOutstanding")
	}

	var r0 []supply.MemberItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]supply.MemberItem, error)); ok {
		return rf(ctx, serverID, threadID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []supply.MemberItem); ok {
		r0 = rf(ctx, serverID, threadID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]supply.MemberItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, serverID, threadID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MemberOutstanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberOutstanding'
type MockRepository_MemberOutstanding_Call struct {
	*mock.Call
}

// MemberOutstanding is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - userID string
func (_e *MockRepository_Expecter) MemberOutstanding(ctx interface{}, serverID interface{}, threadID interface{}, userID interface{}) *MockRepository_MemberOutstanding_Call {
	return &MockRepository_MemberOutstanding_Call{Call: _e.mock.On("MemberOutstanding", ctx, serverID, threadID, userID)}
}

func (_c *MockRepository_MemberOutstanding_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, userID string)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) Return(_a0 []supply.MemberItem, _a1 error) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MemberOutstanding_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) ([]supply.MemberItem, error)) *MockRepository_MemberOutstanding_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with given fields: ctx, serverID, threadID
func (_m *MockRepository) Progress(ctx context.Context, serverID uuid.UUID, threadID string) (supply.Progress, error) {
	ret := _m.Called(ctx, serverID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 supply.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (supply.Progress, error)); ok {
		return rf(ctx, serverID, threadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) supply.Progress); ok {
		r0 = rf(ctx, serverID, threadID)
	} else {
		r0 = ret.Get(0).(supply.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, serverID, threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockRepository_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) Progress(ctx interface{}, serverID interface{}, threadID interface{}) *MockRepository_Progress_Call {
	return &MockRepository_Progress_Call{Call: _e.mock.On("Progress", ctx, serverID, threadID)}
}

func (_c *MockRepository_Progress_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string)) *MockRepository_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_Progress_Call) Return(_a0 supply.Progress, _a1 error) *MockRepository_Progress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Progress_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (supply.Progress, error)) *MockRepository_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByID provides a mock function with given fields: ctx, requestID
func (_m *MockRepository) ProgressByID(ctx context.Context, requestID uuid.UUID) (supply.Progress, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByID")
	}

	var r0 supply.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (supply.Progress, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) supply.Progress); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Get(0).(supply.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByID'
type MockRepository_ProgressByID_Call struct {
	*mock.Call
}

// ProgressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByID(ctx interface{}, requestID interface{}) *MockRepository_ProgressByID_Call {
	return &MockRepository_ProgressByID_Call{Call: _e.mock.On("ProgressByID", ctx, requestID)}
}

func (_c *MockRepository_ProgressByID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRepository_ProgressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByID_Call) Return(_a0 supply.Progress, _a1 error) *MockRepository_ProgressByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (supply.Progress, error)) *MockRepository_ProgressByID_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByIDOwned provides a mock function with given fields: ctx, serverID, ownerUserID, requestID
func (_m *MockRepository) ProgressByIDOwned(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID) (supply.Progress, error) {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByIDOwned")
	}

	var r0 supply.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (supply.Progress, error)); ok {
		return rf(ctx, serverID, ownerUserID, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) supply.Progress); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID)
	} else {
		r0 = ret.Get(0).(supply.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, ownerUserID, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByIDOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByIDOwned'
type MockRepository_ProgressByIDOwned_Call struct {
	*mock.Call
}

// ProgressByIDOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByIDOwned(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}) *MockRepository_ProgressByIDOwned_Call {
	return &MockRepository_ProgressByIDOwned_Call{Call: _e.mock.On("ProgressByIDOwned", ctx, serverID, ownerUserID, requestID)}
}

func (_c *MockRepository_ProgressByIDOwned_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID)) *MockRepository_ProgressByIDOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByIDOwned_Call) Return(_a0 supply.Progress, _a1 error) *MockRepository_ProgressByIDOwned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByIDOwned_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (supply.Progress, error)) *MockRepository_ProgressByIDOwned_Call {
	_c.Call.Return(run)
	return _c
}

// ProgressByItemOwned provides a mock function with given fields: ctx, serverID, ownerUserID, itemID
func (_m *MockRepository) ProgressByItemOwned(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID) (supply.Progress, error) {
	ret := _m.Called(ctx, serverID, ownerUserID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressByItemOwned")
	}

	var r0 supply.Progress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (supply.Progress, error)); ok {
		return rf(ctx, serverID, ownerUserID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) supply.Progress); ok {
		r0 = rf(ctx, serverID, ownerUserID, itemID)
	} else {
		r0 = ret.Get(0).(supply.Progress)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, ownerUserID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ProgressByItemOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProgressByItemOwned'
type MockRepository_ProgressByItemOwned_Call struct {
	*mock.Call
}

// ProgressByItemOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - itemID uuid.UUID
func (_e *MockRepository_Expecter) ProgressByItemOwned(ctx interface{}, serverID interface{}, ownerUserID interface{}, itemID interface{}) *MockRepository_ProgressByItemOwned_Call {
	return &MockRepository_ProgressByItemOwned_Call{Call: _e.mock.On("ProgressByItemOwned", ctx, serverID, ownerUserID, itemID)}
}

func (_c *MockRepository_ProgressByItemOwned_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID)) *MockRepository_ProgressByItemOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ProgressByItemOwned_Call) Return(_a0 supply.Progress, _a1 error) *MockRepository_ProgressByItemOwned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ProgressByItemOwned_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (supply.Progress, error)) *MockRepository_ProgressByItemOwned_Call {
	_c.Call.Return(run)
	return _c
}

// RecreatePost provides a mock function with given fields: ctx, requestID
func (_m *MockRepository) RecreatePost(ctx context.Context, requestID uuid.UUID) error {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for RecreatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RecreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecreatePost'
type MockRepository_RecreatePost_Call struct {
	*mock.Call
}

// RecreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) RecreatePost(ctx interface{}, requestID interface{}) *MockRepository_RecreatePost_Call {
	return &MockRepository_RecreatePost_Call{Call: _e.mock.On("RecreatePost", ctx, requestID)}
}

func (_c *MockRepository_RecreatePost_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRepository_RecreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RecreatePost_Call) Return(_a0 error) *MockRepository_RecreatePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RecreatePost_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRepository_RecreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: ctx, serverID, threadID, gdid, userID, qty
func (_m *MockRepository) Release(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int) error {
	ret := _m.Called(ctx, serverID, threadID, gdid, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r0 = rf(ctx, serverID, threadID, gdid, userID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - gdid string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Release(ctx interface{}, serverID interface{}, threadID interface{}, gdid interface{}, userID interface{}, qty interface{}) *MockRepository_Release_Call {
	return &MockRepository_Release_Call{Call: _e.mock.On("Release", ctx, serverID, threadID, gdid, userID, qty)}
}

func (_c *MockRepository_Release_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int)) *MockRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Release_Call) Return(_a0 error) *MockRepository_Release_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Release_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) error) *MockRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function with given fields: ctx, serverID, ownerUserID, itemID
func (_m *MockRepository) RemoveItem(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, serverID, ownerUserID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (int, error)); ok {
		return rf(ctx, serverID, ownerUserID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) int); ok {
		r0 = rf(ctx, serverID, ownerUserID, itemID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, serverID, ownerUserID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - itemID uuid.UUID
func (_e *MockRepository_Expecter) RemoveItem(ctx interface{}, serverID interface{}, ownerUserID interface{}, itemID interface{}) *MockRepository_RemoveItem_Call {
	return &MockRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, serverID, ownerUserID, itemID)}
}

func (_c *MockRepository_RemoveItem_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID)) *MockRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RemoveItem_Call) Return(_a0 int, _a1 error) *MockRepository_RemoveItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_RemoveItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (int, error)) *MockRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// Republish provides a mock function with given fields: ctx, serverID, ownerUserID, requestID
func (_m *MockRepository) Republish(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Republish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Republish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Republish'
type MockRepository_Republish_Call struct {
	*mock.Call
}

// Republish is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) Republish(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}) *MockRepository_Republish_Call {
	return &MockRepository_Republish_Call{Call: _e.mock.On("Republish", ctx, serverID, ownerUserID, requestID)}
}

func (_c *MockRepository_Republish_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID)) *MockRepository_Republish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Republish_Call) Return(_a0 error) *MockRepository_Republish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Republish_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) error) *MockRepository_Republish_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function with given fields: ctx, serverID, threadID, gdid, userID, qty
func (_m *MockRepository) Reserve(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int) error {
	ret := _m.Called(ctx, serverID, threadID, gdid, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r0 = rf(ctx, serverID, threadID, gdid, userID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockRepository_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - threadID string
//   - gdid string
//   - userID string
//   - qty int
func (_e *MockRepository_Expecter) Reserve(ctx interface{}, serverID interface{}, threadID interface{}, gdid interface{}, userID interface{}, qty interface{}) *MockRepository_Reserve_Call {
	return &MockRepository_Reserve_Call{Call: _e.mock.On("Reserve", ctx, serverID, threadID, gdid, userID, qty)}
}

func (_c *MockRepository_Reserve_Call) Run(run func(ctx context.Context, serverID uuid.UUID, threadID string, gdid string, userID string, qty int)) *MockRepository_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_Reserve_Call) Return(_a0 error) *MockRepository_Reserve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Reserve_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string, int) error) *MockRepository_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeliveryLocation provides a mock function with given fields: ctx, serverID, ownerUserID, requestID, gdid, gdVersion
func (_m *MockRepository) SetDeliveryLocation(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, gdid string, gdVersion string) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID, gdid, gdVersion)

	if len(ret) == 0 {
		panic("no return value specified for SetDeliveryLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID, gdid, gdVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetDeliveryLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeliveryLocation'
type MockRepository_SetDeliveryLocation_Call struct {
	*mock.Call
}

// SetDeliveryLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
//   - gdid string
//   - gdVersion string
func (_e *MockRepository_Expecter) SetDeliveryLocation(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}, gdid interface{}, gdVersion interface{}) *MockRepository_SetDeliveryLocation_Call {
	return &MockRepository_SetDeliveryLocation_Call{Call: _e.mock.On("SetDeliveryLocation", ctx, serverID, ownerUserID, requestID, gdid, gdVersion)}
}

func (_c *MockRepository_SetDeliveryLocation_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, gdid string, gdVersion string)) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_SetDeliveryLocation_Call) Return(_a0 error) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetDeliveryLocation_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, string, string) error) *MockRepository_SetDeliveryLocation_Call {
	_c.Call.Return(run)
	return _c
}

// SetMessageRef provides a mock function with given fields: ctx, serverID, ownerUserID, requestID, guildID, channelID, messageID
func (_m *MockRepository) SetMessageRef(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, guildID string, channelID string, messageID string) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID, guildID, channelID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for SetMessageRef")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID, guildID, channelID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetMessageRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessageRef'
type MockRepository_SetMessageRef_Call struct {
	*mock.Call
}

// SetMessageRef is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
//   - guildID string
//   - channelID string
//   - messageID string
func (_e *MockRepository_Expecter) SetMessageRef(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}, guildID interface{}, channelID interface{}, messageID interface{}) *MockRepository_SetMessageRef_Call {
	return &MockRepository_SetMessageRef_Call{Call: _e.mock.On("SetMessageRef", ctx, serverID, ownerUserID, requestID, guildID, channelID, messageID)}
}

func (_c *MockRepository_SetMessageRef_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, guildID string, channelID string, messageID string)) *MockRepository_SetMessageRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockRepository_SetMessageRef_Call) Return(_a0 error) *MockRepository_SetMessageRef_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetMessageRef_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, string, string, string) error) *MockRepository_SetMessageRef_Call {
	_c.Call.Return(run)
	return _c
}

// SetSystemInfo provides a mock function with given fields: ctx, serverID, ownerUserID, requestID, systemName, systemCode, planet
func (_m *MockRepository) SetSystemInfo(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, systemName string, systemCode string, planet *int) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID, systemName, systemCode, planet)

	if len(ret) == 0 {
		panic("no return value specified for SetSystemInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, string, string, *int) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID, systemName, systemCode, planet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSystemInfo'
type MockRepository_SetSystemInfo_Call struct {
	*mock.Call
}

// SetSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
//   - systemName string
//   - systemCode string
//   - planet *int
func (_e *MockRepository_Expecter) SetSystemInfo(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}, systemName interface{}, systemCode interface{}, planet interface{}) *MockRepository_SetSystemInfo_Call {
	return &MockRepository_SetSystemInfo_Call{Call: _e.mock.On("SetSystemInfo", ctx, serverID, ownerUserID, requestID, systemName, systemCode, planet)}
}

func (_c *MockRepository_SetSystemInfo_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, systemName string, systemCode string, planet *int)) *MockRepository_SetSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string), args[6].(*int))
	})
	return _c
}

func (_c *MockRepository_SetSystemInfo_Call) Return(_a0 error) *MockRepository_SetSystemInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetSystemInfo_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, string, string, *int) error) *MockRepository_SetSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SetThreadID provides a mock function with given fields: ctx, requestID, threadID
func (_m *MockRepository) SetThreadID(ctx context.Context, requestID uuid.UUID, threadID string) error {
	ret := _m.Called(ctx, requestID, threadID)

	if len(ret) == 0 {
		panic("no return value specified for SetThreadID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, requestID, threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetThreadID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThreadID'
type MockRepository_SetThreadID_Call struct {
	*mock.Call
}

// SetThreadID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - threadID string
func (_e *MockRepository_Expecter) SetThreadID(ctx interface{}, requestID interface{}, threadID interface{}) *MockRepository_SetThreadID_Call {
	return &MockRepository_SetThreadID_Call{Call: _e.mock.On("SetThreadID", ctx, requestID, threadID)}
}

func (_c *MockRepository_SetThreadID_Call) Run(run func(ctx context.Context, requestID uuid.UUID, threadID string)) *MockRepository_SetThreadID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_SetThreadID_Call) Return(_a0 error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetThreadID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockRepository_SetThreadID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDetails provides a mock function with given fields: ctx, serverID, ownerUserID, requestID, title, description
func (_m *MockRepository) UpdateDetails(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, title string, description string) error {
	ret := _m.Called(ctx, serverID, ownerUserID, requestID, title, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, requestID, title, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDetails'
type MockRepository_UpdateDetails_Call struct {
	*mock.Call
}

// UpdateDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - requestID uuid.UUID
//   - title string
//   - description string
func (_e *MockRepository_Expecter) UpdateDetails(ctx interface{}, serverID interface{}, ownerUserID interface{}, requestID interface{}, title interface{}, description interface{}) *MockRepository_UpdateDetails_Call {
	return &MockRepository_UpdateDetails_Call{Call: _e.mock.On("UpdateDetails", ctx, serverID, ownerUserID, requestID, title, description)}
}

func (_c *MockRepository_UpdateDetails_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, requestID uuid.UUID, title string, description string)) *MockRepository_UpdateDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateDetails_Call) Return(_a0 error) *MockRepository_UpdateDetails_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateDetails_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, string, string) error) *MockRepository_UpdateDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItemQty provides a mock function with given fields: ctx, serverID, ownerUserID, itemID, qty
func (_m *MockRepository) UpdateItemQty(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID, qty int) error {
	ret := _m.Called(ctx, serverID, ownerUserID, itemID, qty)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemQty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID, int) error); ok {
		r0 = rf(ctx, serverID, ownerUserID, itemID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateItemQty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItemQty'
type MockRepository_UpdateItemQty_Call struct {
	*mock.Call
}

// UpdateItemQty is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID uuid.UUID
//   - ownerUserID string
//   - itemID uuid.UUID
//   - qty int
func (_e *MockRepository_Expecter) UpdateItemQty(ctx interface{}, serverID interface{}, ownerUserID interface{}, itemID interface{}, qty interface{}) *MockRepository_UpdateItemQty_Call {
	return &MockRepository_UpdateItemQty_Call{Call: _e.mock.On("UpdateItemQty", ctx, serverID, ownerUserID, itemID, qty)}
}

func (_c *MockRepository_UpdateItemQty_Call) Run(run func(ctx context.Context, serverID uuid.UUID, ownerUserID string, itemID uuid.UUID, qty int)) *MockRepository_UpdateItemQty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_UpdateItemQty_Call) Return(_a0 error) *MockRepository_UpdateItemQty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateItemQty_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID, int) error) *MockRepository_UpdateItemQty_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
