// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	gamedata "github.com/kweezl/spacecraft-corporation/internal/gamedata"
	i18n "github.com/kweezl/spacecraft-corporation/internal/i18n"
	mock "github.com/stretchr/testify/mock"
)

// MockGameSearch is an autogenerated mock type for the GameSearch type
type MockGameSearch struct {
	mock.Mock
}

type MockGameSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameSearch) EXPECT() *MockGameSearch_Expecter {
	return &MockGameSearch_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: kind, lang, query, limit
func (_m *MockGameSearch) Search(kind gamedata.Kind, lang i18n.Language, query string, limit int) ([]gamedata.Hit, error) {
	ret := _m.Called(kind, lang, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []gamedata.Hit
	var r1 error
	if rf, ok := ret.Get(0).(func(gamedata.Kind, i18n.Language, string, int) ([]gamedata.Hit, error)); ok {
		return rf(kind, lang, query, limit)
	}
	if rf, ok := ret.Get(0).(func(gamedata.Kind, i18n.Language, string, int) []gamedata.Hit); ok {
		r0 = rf(kind, lang, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gamedata.Hit)
		}
	}

	if rf, ok := ret.Get(1).(func(gamedata.Kind, i18n.Language, string, int) error); ok {
		r1 = rf(kind, lang, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameSearch_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockGameSearch_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - kind gamedata.Kind
//   - lang i18n.Language
//   - query string
//   - limit int
func (_e *MockGameSearch_Expecter) Search(kind interface{}, lang interface{}, query interface{}, limit interface{}) *MockGameSearch_Search_Call {
	return &MockGameSearch_Search_Call{Call: _e.mock.On("Search", kind, lang, query, limit)}
}

func (_c *MockGameSearch_Search_Call) Run(run func(kind gamedata.Kind, lang i18n.Language, query string, limit int)) *MockGameSearch_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gamedata.Kind), args[1].(i18n.Language), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockGameSearch_Search_Call) Return(_a0 []gamedata.Hit, _a1 error) *MockGameSearch_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameSearch_Search_Call) RunAndReturn(run func(gamedata.Kind, i18n.Language, string, int) ([]gamedata.Hit, error)) *MockGameSearch_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameSearch creates a new instance of MockGameSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameSearch {
	mock := &MockGameSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
